### ISSUE TITLE
Prompt text in sqlite3 CLI (new in 3.12) is Linux oriented and doesn't apply to Windows

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#102628]
# Bug report
The command line command `python3.12 -m sqlite3` gives a prompt stating "[...]Type ".help" for more information; type ".quit" or CTRL-D to quit."
But on Windows, the Unixism `CTRL-D` doesn't work (instead, and after adding ";" and "ENTER", it reports: "OperationalError (SQLITE_ERROR): unrecognized token: "♦"" ); `CTRL-Z` _does_ work on Windows (but not on Linux, I guess).

Request to clarify the prompt.

# Environment
- CPython: Python 3.12.0a6 (tags/v3.12.0a6:f9774e5, Mar  7 2023, 23:52:43) [MSC v.1934 64 bit (AMD64)]
- Operating system: MS Windows 3.11 Pro
- Architecture: Intel i5

### Linked PRs
* gh-103898
* gh-103945

**Comment by terryjreedy** [comment]
I corrected `sqlite` to `sqlite3` in the startup command.  ^Z must be followed by <RETURN> to exit, but windows users should know that.

`CTRL-D` is in sqlite3.__main__ in the 'banner' f-string.  To fix, replace `D` with `{exitchar}` and define exitchar above the banner assignment.  I may do it later.

**Comment by erlend-aasland** [comment]
Perhaps the easiest thing to do would be to adjust the banner depending on which platform we're running on. For *nix, we can recommend CTRL-D, for Windows, we can recommend CTRL-Z.

**Comment by erlend-aasland** [comment]
Reopening, as the prompt is still incorrect in IDLE on Windows.
