### ISSUE TITLE
Queue get timout parameter does not use a monotonic timer

### ISSUE THREAD

**Issue by fdirosa4188** [python/cpython#104509]
It is clear looking at the source code that the Queue class uses time() and other non-monotonic timing sources.  So if a queue get function is called with a timeout value and the system time is changed during that get it could end up waiting in the get for potentially days.  The easiest way to reproduce is to set the timeout in the get to 5 minutes and which it is waiting on the queue to get an entry set the system clock back a few years.  You will notice it will not exit the get.

**Comment by arhadthedev** [comment]
@rhettinger (as a `queue` module expert)

**Comment by Agent-Hellboy** [comment]
do you have a reproducible code?
it's monotonic
https://github.com/python/cpython/blob/0bb61dd5b0ffc248e18f1b33cddd18788f28e60a/Lib/queue.py#L7

**Comment by fdirosa4188** [comment]
I am using Python 3.8.6 on Linux.
Attached is python code that reproduces this problem.  I set the a specific date/time before the queue.get blocking call with a 10 second timeout and then change the date/time to a different date/time during the queue.get and it does not return after 10 seconds.

There is a variable in the attached script called Make_It_Fail that is set to True.  You can set it to False to see how the script works without date/time changes then set it to True to see how queue.get does not return after 10 seconds has elapsed.
[queue_timeout_test.py.txt](https://github.com/python/cpython/files/11499572/queue_timeout_test.py.txt)

**Comment by aludwig98** [comment]
This seems to have been resolved in Python 3.9, 3.10. 

See here: https://github.com/python/cpython/issues/85876

**Comment by fdirosa4188** [comment]
I tried my queue_timeout.test.py script on Python 3.11 and it still does not timeout after 10 seconds.  The queue.get() function blocks and seems to still be effected by changes to the system time on Linux.

**Comment by danik292** [comment]
Ok how to fix it

**Comment by duaneg** [comment]
I can't reproduce the bug on current HEAD (v3.15-alpha), but then I can't reproduce it on v3.11.0 either.  In both cases it produces the correct, expected output:
```
Date/Time before queue.get(): 05/18/2024 23:34:43
Calling queue get with blocking and 10 seconds timeout
Date/Time during queue.get(): 05/18/2023 18:34:43
10.00 seconds has elapsed and it is not blocked
```

As @Agent-Hellboy says, the queue code itself uses a monotonic clock, and after #28662 so does the underlying lock the condition variable waits on.

@fdirosa4188 please re-test and close if confirmed.
