### ISSUE TITLE
Cannot build 3.11.4 on Raspberry pi

### ISSUE THREAD

**Issue by TheCarpetMerchant** [python/cpython#105706]
# Bug report

During `make -j 4` after having configured optimizations :
The installed version of openssl is `1.1.1n-0+deb11u4+rpt1`
```
fatal error: ffi.h: No such file or directory
  118 | #include <ffi.h>
      |          ^~~~~~~
compilation terminated.
gcc -pthread -shared -fno-semantic-interposition build/temp.linux-aarch64-3.11/home/sure/Python-3.11.4/Modules/xxlimited_35.o -L/usr/lib/arm-linux-gnueabihf -L/usr/local/lib -o build/lib.linux-aarch64-3.11/xxlimited_35.cpython-311-arm-linux-gnueabihf.so
gcc -pthread -shared -fno-semantic-interposition build/temp.linux-aarch64-3.11/home/sure/Python-3.11.4/Modules/_decimal/_decimal.o Modules/_decimal/libmpdec/libmpdec.a -L/usr/lib/arm-linux-gnueabihf -L/usr/local/lib -lm -o build/lib.linux-aarch64-3.11/_decimal.cpython-311-arm-linux-gnueabihf.so

The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _hashlib           
_lzma                 _ssl                  _tkinter           
_uuid                 readline                                 
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py have not
been built, they are *disabled* by configure:
_sqlite3                                                       


Failed to build these modules:
_ctypes                                                        


Could not build the ssl module!
Python requires a OpenSSL 1.1.1 or newer
```

# Your environment

- Operating system and architecture: aarch 64 (Raspbian 11), Raspberry Pi 4 Model B 4GB

**Comment by chgnrdv** [comment]
Have you installed `libssl-dev` package? I'm not Raspbian user, but pretty sure that installation process is the same as in Debian.

**Comment by TheCarpetMerchant** [comment]
I've installed the following package after reading a few stackoverflow posts :
`libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev`

**Comment by ronaldoussoren** [comment]
Try installing ``libffi-dev`` as well, that should fix the build error for ``_ctypes``.  [The devguide](https://devguide.python.org/getting-started/setup-building/) contains a list of packages to install on Debian, which should also work on Raspian. In short:

```sh
$ sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev
```

That command includes a number of additional packages relative to what you already already installed.

**Comment by TheCarpetMerchant** [comment]
Still getting the same error, albeit with fewer missing packages :
```
_bz2                  _dbm                  _gdbm
_hashlib              _lzma                 _ssl
_tkinter              _uuid                 readline
```

**Comment by ronaldoussoren** [comment]
It's hard to say without seeing a full build log, but this likely still indicates that some build requirements are missing, e.g. the various '-dev ' packages that should be installed according to the devguide.

**Comment by TheCarpetMerchant** [comment]
Where can I find the 'deb-src' url for Raspbian ?

The following packages are installed :
```
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
build-essential is already the newest version (12.9).
gdb is already the newest version (10.1-1.7).
lcov is already the newest version (1.14-2).
libbz2-dev is already the newest version (1.0.8-4).
libffi-dev is already the newest version (3.3-6).
libgdbm-compat-dev is already the newest version (1.19-2).
libgdbm-dev is already the newest version (1.19-2).
liblzma-dev is already the newest version (5.2.5-2.1~deb11u1).
libncurses5-dev is already the newest version (6.2+20201114-2+deb11u1).
libreadline-dev is already the newest version (8.1-1).
libsqlite3-dev is already the newest version (3.34.1-3).
lzma is already the newest version (9.22-2.2).
lzma-dev is already the newest version (9.22-2.2).
pkg-config is already the newest version (0.29.2-1).
tk-dev is already the newest version (8.6.11+1).
uuid-dev is already the newest version (2.36.1-8+deb11u1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2+deb11u2).
libssl-dev is already the newest version (1.1.1n-0+deb11u4+rpt1).
pkg-config is already the newest version (0.29.2-1).
The following package was automatically installed and is no longer required:
  libreadline5
```

**Comment by erlend-aasland** [comment]
You should be able to run `./.github/workflows/posix-deps-apt.sh` from within your git cloned CPython repo, which will install pretty much all dependencies for you.

**Comment by StanFromIreland** [comment]
Was this resolved successfully? The ARM Raspbian buildbot is green on 3.11 (see [log](https://buildbot.python.org/#/builders/980)) and so is the ARM64 Raspbian buildbot for > 3.12 (see [green fields](https://buildbot.python.org/#/workers/117) [ignore the yellow "dandelions"] :-).

cc @gpshead (PS. you are not listed in the devguide beside Raspbian)

**Comment by gpshead** [comment]
closing as this is just a matter of installing the required dependencies.  not rpi specific, anything debian based needs deps installed.
