### ISSUE TITLE
SyntaxWarnings in `test_fstring`

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#105915]
# Bug report

Running `python -m test test_fstring` on `main` results in several `SyntaxWarnings` being emitted.

If I just run `python -m test test_fstring` locally, I get this:

```pytb
C:\Users\alexw\coding\cpython>python -m test test_fstring
Running Release|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_fstring
C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py:775: SyntaxWarning: invalid escape sequence '\_'
  exec('f"{F():¯\_(ツ)_/¯}"', {'F': CustomFormat})

== Tests result: SUCCESS ==

1 test OK.

Total duration: 14.5 sec
Tests result: SUCCESS
```

If I run `python -We -m test test_fstring -vv`, I get a different selection of SyntaxWarnings:

```pytb
======================================================================
ERROR: test_fstring_backslash_before_double_bracket (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket) (case="f'\\{{\\}}'", expected_result='\\{\\}')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1041, in test_fstring_backslash_before_double_bracket
    result = eval(case)
             ^^^^^^^^^^
  File "<string>", line 1
    f'\{{\}}'
            ^
SyntaxError: invalid escape sequence '\{'

======================================================================
ERROR: test_fstring_backslash_before_double_bracket (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket) (case="f'\\{{'", expected_result='\\{')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1041, in test_fstring_backslash_before_double_bracket
    result = eval(case)
             ^^^^^^^^^^
  File "<string>", line 1
    f'\{{'
         ^
SyntaxError: invalid escape sequence '\{'

======================================================================
ERROR: test_fstring_backslash_before_double_bracket (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket) (case="f'\\{{{1+1}'", expected_result='\\{2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1041, in test_fstring_backslash_before_double_bracket
    result = eval(case)
             ^^^^^^^^^^
  File "<string>", line 1
    f'\{{{1+1}'
              ^
SyntaxError: invalid escape sequence '\{'

======================================================================
ERROR: test_fstring_backslash_before_double_bracket (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket) (case="f'\\}}{1+1}'", expected_result='\\}2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1041, in test_fstring_backslash_before_double_bracket
    result = eval(case)
             ^^^^^^^^^^
  File "<string>", line 1
    f'\}}{1+1}'
              ^
SyntaxError: invalid escape sequence '\}'

======================================================================
ERROR: test_fstring_backslash_before_double_bracket (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket) (case="f'{1+1}\\}}'", expected_result='2\\}')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1041, in test_fstring_backslash_before_double_bracket
    result = eval(case)
             ^^^^^^^^^^
  File "<string>", line 1
    f'{1+1}\}}'
              ^
SyntaxError: invalid escape sequence '\}'

----------------------------------------------------------------------
Ran 80 tests in 14.399s

FAILED (errors=5)
test test_fstring failed
test_fstring failed (5 errors)

== Tests result: FAILURE ==

1 test failed:
    test_fstring

Total duration: 14.6 sec
Tests result: FAILURE
```

# Your environment

```
Python 3.13.0a0 (heads/main:ab3823a97b, Jun 19 2023, 14:46:42) [MSC v.1932 64 bit (AMD64)] on win32
```

### Linked PRs
* gh-105940
* gh-105942
* gh-105943
* gh-105945

**Comment by sunmy2019** [comment]
The first should be
```diff
-            exec('f"{F():¯\_(ツ)_/¯}"', {'F': CustomFormat})
+            exec(r'f"{F():¯\_(ツ)_/¯}"', {'F': CustomFormat})
```

I am wondering why the second test is reporting errors.

**Comment by sobolevn** [comment]
I cannot reproduce this locally on macOS (using 155577de1b6a7f4404b2bf90bcc1a588201550da), output for me:

```
» ./python.exe -m test test_fstring   
0:00:00 load avg: 1.06 Run tests sequentially
0:00:00 load avg: 1.06 [1/1] test_fstring

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1.6 sec
Tests result: SUCCESS
```

**Comment by AlexWaygood** [comment]
> I cannot reproduce this locally on macOS (using [155577d](https://github.com/python/cpython/commit/155577de1b6a7f4404b2bf90bcc1a588201550da)), output for me:
> 
> ```
> » ./python.exe -m test test_fstring   
> 0:00:00 load avg: 1.06 Run tests sequentially
> 0:00:00 load avg: 1.06 [1/1] test_fstring
> 
> == Tests result: SUCCESS ==
> 
> 1 test OK.
> 
> Total duration: 1.6 sec
> Tests result: SUCCESS
> ```

I'm certain this reproduced consistently for me when I filed the report, but I can also no longer reproduce the first issue. I have no idea why this is.

I can still reproduce the test failures when running the test with `-We`, however.

**Comment by lysnikolaou** [comment]
Fixed in #105938 and #105940.

**Comment by lysnikolaou** [comment]
I just now realize I could've left #105940 for any of the upcoming sprints, since it was an easy fix. Sorry for that! ❤️

**Comment by AlexWaygood** [comment]
Hmm, even with a fresh build on `main`, I still get one failure when running `python -We -m test test_fstring -v`:

```pytb
======================================================================
ERROR: test_fstring_backslash_before_double_bracket_warns_once (test.test_fstring.TestCase.test_fstring_backslash_before_double_bracket_warns_once)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_fstring.py", line 1052, in test_fstring_backslash_before_double_bracket_warns_once
    eval(r"f'\{{'")
  File "<string>", line 1
    f'\{{'
       ^
SyntaxError: invalid escape sequence '\{'

----------------------------------------------------------------------
Ran 81 tests in 30.549s

FAILED (errors=1)
test test_fstring failed
test_fstring failed (1 error) in 30.7 sec

== Tests result: FAILURE ==

1 test failed:
    test_fstring

Total duration: 30.8 sec
Tests result: FAILURE
```
