### ISSUE TITLE
Core dump with specific call of find_frozen

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126171]
# Crash report

### What happened?

```bash
>>> from importlib import _imp
>>> _imp.find_frozen("zipimport", withdata=True)
python3: Objects/memoryobject.c:733: PyMemoryView_FromMemory: Assertion `mem != ((void *)0)' failed.
Aborted (core dumped)
```

python is configured with `--with-pydebug --with-trace-refs --with-assertions`

I think it [happens here](https://github.com/python/cpython/blob/00e5ec0d35193c1665e5c0cfe5ef82eed270d0f4/Python/import.c#L4416C1-L4421C6)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.9 (main, Oct 30 2024, 09:46:33) [GCC 13.2.0]

### Linked PRs
* gh-126566
* gh-126567
* gh-126568

**Comment by sobolevn** [comment]
@federicovalenso how do you find these problems? Do you use some kind of tooling for that?

**Comment by ZeroIntensity** [comment]
I'm guessing it's a static analyzer. Anyways, I can take a look at this later today, unless @picnixz has already started working on it.

**Comment by picnixz** [comment]
> I'm guessing it's a static analyzer. Anyways, I can take a look at this later today, unless \@picnixz has already started working on it.

Please do so! I have some ongoing work elsewhere but I don't mind reviewing it!

**Comment by federicovalenso** [comment]
I'm sorry for late answer.

> I'm guessing it's a static analyzer.

@sobolevn , @ZeroIntensity , you're right.

**Comment by ZeroIntensity** [comment]
We're fine with it as long as the crashes are actual bugs and not false positives (there have been false positive reports from static analyzers here in the past). But you seem to know what's real and what's not, keep doing what you're doing :)

**Comment by picnixz** [comment]
@ZeroIntensity I have some time now; do you want me to take on that task or were you already working on it?

**Comment by ZeroIntensity** [comment]
Go for it, I didn't get to this yesterday. I'll be happy to review your PR!

**Comment by picnixz** [comment]
Actually, I couldn't reproduce it on 3.12+ (even with the correct flags). It appears that it has been patched at some point. @federicovalenso can you 1) verify this 2) try to run your static analyzer tool on 3.12+ builds instead please? Thank you in advance!

**Comment by federicovalenso** [comment]
@picnixz , yeah, I'll do that, but it requires some time.

**Comment by picnixz** [comment]
No worries! If you can compile 3.12 on your side and try the same reproducer (just to see if it's my machine that is special or not) to confirm whether this bug still happens or not, I'd be willing to keep the issue opened (no need to bisect the commit for now). Otherwise, in order not to have a `pending` label for too long, I'd suggest closing this issue for now and come back later.

**Comment by sobolevn** [comment]
> Otherwise, in order not to have a pending label for too long, I'd suggest closing this issue for now and come back later.

There's no real problem in having an issue with the "pending" label :)
Let's resolve the issue first: with finding the proper reproducer or with finding that it was fixed already. And then we can completelly close the issue.

**Comment by federicovalenso** [comment]
@picnixz , I couldn't reproduce it on 3.12+ too. Also I did static analysis, it still continues to complain about the same place in the code.

**Comment by picnixz** [comment]
> Also I did static analysis, it still continues to complain about the same place in the code.

What does it say for this line? does it say that it's unsafe, or can lead to a core dump? (or something like that?)

**Comment by picnixz** [comment]
Ah I see. Yes, we should use a `Py_XDECREF` just in case.

**Comment by picnixz** [comment]
@federicovalenso If you want to make a PR, go ahead, otherwise I'll do it a bit later.
