### ISSUE TITLE
Docs: EPUB builds are broken

### ISSUE THREAD

**Issue by m-aciek** [python/cpython#136155]
# Documentation

https://github.com/python/cpython/pull/132220 has broken EPUB builds of documentation. This has been only partially fixed in https://github.com/python/cpython/pull/133720, because yet configuration of `sphinxext-opengraph` adds not closed tags to every page.

![Image](https://github.com/user-attachments/assets/7841d6d9-4ea1-43f5-9e43-6a40912d0753)

https://github.com/sphinx-doc/sphinxext-opengraph/issues/136 and https://github.com/sphinx-doc/sphinxext-opengraph/pull/137 have been opened upstream, but the PR is not merged.

Status update [2025-07-14]: now (after skipping OpenGraph custom tags in Docs `conf.py`) only 8 chapters fail to render in EPUB format. It can be addressed by any of https://github.com/sphinx-doc/sphinxext-opengraph/pull/120 and https://github.com/sphinx-doc/sphinxext-opengraph/pull/137, as far as I'm concerned. Adding a CI check definitely should help with the stability of EPUB build. Last year Inada made an effort to fix the EPUB (https://github.com/python/cpython/issues/118689).

### Linked PRs
* gh-136187
* gh-134074
* gh-136382
* gh-136383
* gh-136406
* gh-137348
* gh-137349
* gh-137350
* gh-137351
* gh-137393
* gh-137431
* gh-137432
* gh-137538
* gh-137539
* gh-138741
* gh-145471

**Comment by hugovk** [comment]
Would you like to open a PR with your tags suggestion from https://github.com/python/cpython/pull/134071#issuecomment-2912189708?

Otherwise, let's do https://github.com/python/cpython/pull/134071.

**Comment by m-aciek** [comment]
I've figured out the tags approach and confirmed it works locally: #136187.

**Comment by hugovk** [comment]
https://github.com/python/cpython/pull/136187 has improved it but not fixed them all: https://github.com/python/cpython/pull/136187#issuecomment-3046368757

They are:

```
FATAL - RSC-016 - Python.epub/howto/descriptor.xhtml:11:78 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/howto/logging-cookbook.xhtml:11:62 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/howto/logging.xhtml:11:62 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/howto/regex.xhtml:11:64 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/whatsnew/3.4.xhtml:11:66 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/whatsnew/3.5.xhtml:11:71 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/whatsnew/3.6.xhtml:11:71 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
FATAL - RSC-016 - Python.epub/whatsnew/3.7.xhtml:11:70 - Fatal Error while parsing file: The value of attribute "content" associated with an element type "meta" must not contain the '<' character.
```

Here's the first couple, the rest are also all similar email address tags:


```xhtml
<meta property="og:description" content="Author, Raymond Hettinger,, Contact,<python at rcn dot com>,. Contents: Descriptor Guide- Primer- Simple example: A descriptor that returns a constant, Dynamic lookups, Managed attributes, Customiz..." />
```

```xhtml
<meta property="og:description" content="Author, Vinay Sajip <vinay_sajip at red-dove dot com>,. This page contains a number of recipes related to logging, which have been found useful in the past. For links to tutorial and reference info..." />
```

(macOS tip: opening the EPUB in BBEdit gives a folder-based UI and you can see the plaintext xhtml files inside.)

**Comment by cclauss** [comment]
There is a Python 3.14 release candidate, but it is impossible to download and read the EPUB docs???

**Comment by hugovk** [comment]
@AA-Turner Any chance to merge https://github.com/sphinx-doc/sphinxext-opengraph/pull/137 and make a new release?

**Comment by AA-Turner** [comment]
I've released [`sphinxext-opengraph` v0.11](https://github.com/sphinx-doc/sphinxext-opengraph/releases/tag/v0.11.0) with https://github.com/sphinx-doc/sphinxext-opengraph/pull/120. I'm happy to make another release with https://github.com/sphinx-doc/sphinxext-opengraph/pull/137, I've asked on that PR for a test to demonstrate the problem that it solves.

A

**Comment by m-aciek** [comment]
With #137348 (and #137393) we got rid of all fatal errors. The CI check [reports](https://github.com/python/cpython/actions/runs/17595951163/job/49988139405) now 72 errors and 4 warnings. Though chapters with errors render just fine in my reader (attaching screenshots). Therefore I'm closing the issue. Thank you to all involved!

<img width="1136" height="880" alt="Image" src="https://github.com/user-attachments/assets/045a799e-8926-41fa-b3ab-14c98f2fecf4" />
<img width="1136" height="880" alt="Image" src="https://github.com/user-attachments/assets/b503051c-388e-4e53-9da0-8f7053926857" />

**Comment by hugovk** [comment]
There's still a problem with the 3.12 EPUB: https://github.com/python/cpython/pull/136406#issuecomment-3274530503

Here's an extra backport to fix it: https://github.com/python/cpython/pull/138741

**Comment by m-aciek** [comment]
With 3.12 fixed, let's close

**Comment by hugovk** [comment]
Do we also need to fix the other security branches: 3.9-3.11?

**Comment by AA-Turner** [comment]
#132220 wasn't backported that far, so there shouldn't've been any changes on our side, it would only be if a bad opengraph version is still there.

**Comment by hugovk** [comment]
https://docs.python.org/3.11/download.html still has a bad EPUB: https://docs.python.org/3.11/archives/python-3.11.13-docs.epub

3.9 and 3.10 are good.

**Comment by hugovk** [comment]
Looking good now, I checked 3.9, 3.11 and 3.14 🚀
