### ISSUE TITLE
GC segfault with free threading

### ISSUE THREAD

**Issue by kevmo314** [python/cpython#141965]
# Crash report

### What happened?

This code segfaults for me

```python
import threading
import gc
import torch

def main():
    def worker(wid):
        for i in range(100):
            t = torch.zeros(1000)
            cond = threading.Condition()
            if i % 10 == 0:
                gc.collect()
        print(f"W{wid} done")
    threads = [threading.Thread(target=worker, args=(i,)) for i in range(40)]
    for t in threads: t.start()
    for t in threads: t.join()
    print("  PASSED")

if __name__ == "__main__":
    main()
```

I am unclear why. I haven't been able to reproduce it without pytorch and even stranger is that the `threading.Condition()` is not used. It leads me to think there's a race in the garbage collection process and the tensor + Condition happen to trigger some specific states but I haven't been able to characterize that yet.

### CPython versions tested on:

3.14

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0 free-threading build (main, Nov 19 2025, 22:48:09) [Clang 21.1.4 ]

**Comment by kumaraditya303** [comment]
Can you share the stacktrace of the crash?

**Comment by yihong0618** [comment]
> Can you share the stacktrace of the crash?

I can reproducer

```bt
Thread 11 "Thread-3 (worke" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xffffc0ddf100 (LWP 41166)]
_mi_segment_page_of (segment=<optimized out>, p=0xffffc0ddf8c0)
    at ./Include/internal/mimalloc/mimalloc/internal.h:438
warning: 438	./Include/internal/mimalloc/mimalloc/internal.h: No such file or directory
(gdb) bt
#0  _mi_segment_page_of (segment=<optimized out>, p=0xffffc0ddf8c0)
    at ./Include/internal/mimalloc/mimalloc/internal.h:438
#1  _mi_free_delayed_block (block=0xffffc0ddf8c0)
    at Objects/mimalloc/alloc.c:616
#2  0x0000aaaaaadee92c in _mi_heap_delayed_free_partial (heap=<optimized out>)
    at Objects/mimalloc/page.c:333
#3  _mi_malloc_generic (heap=<optimized out>, size=<optimized out>, 
    zero=<optimized out>, huge_alignment=0) at Objects/mimalloc/page.c:943
#4  0x0000aaaaaadfe040 in PyObject_Malloc (size=281473902990048)
    at Objects/obmalloc.c:1478
#5  _PyObject_MallocWithType (tp=0x39cbf4cdc00, size=281473902990048)
    at ./Include/internal/pycore_object_alloc.h:46
#6  _PyType_AllocNoTrack (type=<optimized out>, nitems=<optimized out>)
    at Objects/typeobject.c:2360
#7  PyType_GenericAlloc (type=0x39cbf4cdc00, nitems=0)
    at Objects/typeobject.c:2391
#8  0x0000fffff6cb5264 in THPVariable_NewWithVar(_typeobject*, at::TensorBase const&, bool, std::optional<bool>) ()
   from /home/hyi/py314/.venv/lib/python3.14t/site-packages/torch/lib/libtorch_python.so
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x0000fffff69ab194 in torch::autograd::THPVariable_zeros(_object*, _object*, _object*) ()
   from /home/hyi/py314/.venv/lib/python3.14t/site-packages/torch/lib/libtorch_python.so
#10 0x0000aaaaaade3ef0 in cfunction_call (
    func=<built-in method zeros of type object at remote 0xfffff771bd78>, 
    args=<unknown at remote 0xffffc00052e0>, kwargs=0x0)
    at Objects/methodobject.c:564
#11 0x0000aaaaaae48458 in _PyObject_MakeTpCall (tstate=0xaaaab57a6d10, 
    callable=<built-in method zeros of type object at remote 0xfffff771bd78>, 
    args=0xffffc0dde250, nargs=<optimized out>, keywords=0x0)
    at Objects/call.c:242
#12 _PyObject_VectorcallTstate (tstate=0xaaaab57a6d10, 
    callable=<built-in method zeros of type object at remote 0xfffff771bd78>, 
    args=0xffffc0dde250, nargsf=<optimized out>, kwnames=0x0)
    at ./Include/internal/pycore_call.h:167
#13 PyObject_Vectorcall (
    callable=<built-in method zeros of type object at remote 0xfffff771bd78>, 
    args=0xffffc0dde250, nargsf=<optimized out>, kwnames=0x0)
    at Objects/call.c:327
--Type <RET> for more, q to quit, c to continue without paging--

#14 _TAIL_CALL_CALL_NON_PY_GENERAL (frame=0xfffff78621a8, 
    stack_pointer=0xfffff7862238, tstate=<optimized out>, 
    next_instr=<optimized out>, oparg=1) at Python/generated_cases.c.h:4079
#15 0x0000aaaaaada6a78 in _TAIL_CALL_start_frame (frame=0xfffff78621a8, 
    stack_pointer=0xfffff7862238, tstate=0x39cbe125490, 
    next_instr=0xaaaaabd9c680 <_PyRuntime>, oparg=1)
    at Python/generated_cases.c.h:12509
#16 _PyEval_EvalFrameDefault (tstate=0x39cbe125490, frame=0xfffff78621a8, 
    throwflag=0) at Python/ceval.c:1105
#17 _PyEval_EvalFrame (tstate=0x39cbe125490, frame=0xfffff78621a8, throwflag=0)
    at ./Include/internal/pycore_ceval.h:119
#18 _PyEval_Vector (tstate=0x39cbe125490, func=<optimized out>, 
    locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=<optimized out>) at Python/ceval.c:1965
#19 0x0000aaaaaada6a78 in _PyFunction_Vectorcall (func=<optimized out>, 
    stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
#20 0x0000aaaaaada8c30 in _PyObject_VectorcallTstate (tstate=0xaaaab57a6d10, 
    callable=<function at remote 0x39cbe4e78c0>, args=0xffffc0dde478, nargsf=1, 
    kwnames=0x0) at ./Include/internal/pycore_call.h:169
#21 method_vectorcall (method=<optimized out>, args=0xffffc0dde570, 
--Type <RET> for more, q to quit, c to continue without paging--
    nargsf=<optimized out>, kwnames=<optimized out>) at Objects/classobject.c:73
#22 0x0000aaaaaafbf068 in _PyObject_VectorcallTstate (tstate=0xaaaab57a6d10, 
    callable=<method at remote 0x39cca0d0100>, args=0xffffc0dde570, 
    nargsf=<optimized out>, kwnames=0x0) at ./Include/internal/pycore_call.h:169
#23 context_run (self=<_contextvars.Context at remote 0x39cc42b4180>, 
    args=<optimized out>, nargs=1, kwnames=0x0) at Python/context.c:728
#24 0x0000aaaaaae384f8 in _PyObject_VectorcallTstate (tstate=0xaaaab57a6d10, 
    callable=<unknown at remote 0xcf1bcb7c9a914d86>, args=0xffffc0dde560, 
    nargsf=9223372036854775810, kwnames=0x0)
    at ./Include/internal/pycore_call.h:169
#25 PyObject_Vectorcall (callable=<unknown at remote 0xcf1bcb7c9a914d86>, 
    args=0xffffc0dde560, nargsf=9223372036854775810, kwnames=0x0)
    at Objects/call.c:327
#26 _TAIL_CALL_CALL (frame=<optimized out>, stack_pointer=<optimized out>, 
    tstate=<optimized out>, next_instr=<optimized out>, oparg=1)
    at Python/generated_cases.c.h:1619
#27 0x0000aaaaaada6a78 in _TAIL_CALL_start_frame (frame=0xaaaab57a6d10, 
    stack_pointer=0x28, tstate=0xaaaab57a6d10, next_instr=0x39cc42b4180, 
    oparg=1) at Python/generated_cases.c.h:12509
#28 _PyEval_EvalFrameDefault (tstate=0xaaaab57a6d10, frame=0xaaaab57a6d10, 
--Type <RET> for more, q to quit, c to continue without paging--
    throwflag=0) at Python/ceval.c:1105
#29 _PyEval_EvalFrame (tstate=0xaaaab57a6d10, frame=0xaaaab57a6d10, throwflag=0)
    at ./Include/internal/pycore_ceval.h:119
#30 _PyEval_Vector (tstate=0xaaaab57a6d10, func=<optimized out>, 
    locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=<optimized out>) at Python/ceval.c:1965
#31 0x0000aaaaaada6a78 in _PyFunction_Vectorcall (func=<optimized out>, 
    stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
#32 0x0000aaaaaada8c30 in _PyObject_VectorcallTstate (tstate=0xaaaab57a6d10, 
    callable=<function at remote 0x39cbe4e7980>, args=0xffffc0dde788, nargsf=1, 
    kwnames=0x0) at ./Include/internal/pycore_call.h:169
#33 method_vectorcall (method=<optimized out>, 
    args=0xaaaaabdb89b8 <_PyRuntime+115512>, nargsf=<optimized out>, 
    kwnames=<optimized out>) at Objects/classobject.c:73
#34 0x0000aaaaab0c6b3c in thread_run (boot_raw=0xaaaab2bd3510)
    at ./Modules/_threadmodule.c:359
#35 0x0000aaaaaaff75bc in pythread_wrapper (arg=<optimized out>)
    at Python/thread_pthread.h:242
#36 0x0000fffff7d6bb40 in start_thread (arg=0x80e940) at pthread_create.c:443
#37 0x0000fffff7dd615c in thread_start ()
```

**Comment by kumaraditya303** [comment]
I am able to reproduce as well:
```console
❯ lldb -- ./python.exe main.py
(lldb) target create "./python.exe"
Current executable set to '/Users/kumaraditya/work/cpython/python.exe' (arm64).
(lldb) settings set -- target.run-args  "main.py"
(lldb) r
Process 2358 launched: '/Users/kumaraditya/work/cpython/python.exe' (arm64)
W1 done
W3 done
W2 done
W4 done
W9 done
W7 done
W11 done
W16 done
W5 done
W8 done
Process 2358 stopped
* thread #10, name = 'Thread-16 (worker)', stop reason = EXC_BAD_ACCESS (code=1, address=0x1010005)
    frame #0: 0x00000001000e66f4 python.exe`mi_block_nextx(null=<unavailable>, block=0x0000000001010005, keys=<unavailable>) at internal.h:640:23 [opt] [inlined]
   637    next = (mi_block_t*)mi_ptr_decode(null, mi_atomic_load_relaxed((_Atomic(mi_encoded_t)*)&block->next), keys);
   638    #else
   639    MI_UNUSED(keys); MI_UNUSED(null);
-> 640    next = (mi_block_t*)mi_atomic_load_relaxed((_Atomic(mi_encoded_t)*)&block->next);
   641    #endif
   642    mi_track_mem_noaccess(block,sizeof(mi_block_t));
   643    return next;
Target 0: (python.exe) stopped.
warning: python.exe was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) bt
* thread #10, name = 'Thread-16 (worker)', stop reason = EXC_BAD_ACCESS (code=1, address=0x1010005)
  * frame #0: 0x00000001000e66f4 python.exe`mi_block_nextx(null=<unavailable>, block=0x0000000001010005, keys=<unavailable>) at internal.h:640:23 [opt] [inlined]
    frame #1: 0x00000001000e66f4 python.exe`mi_block_next(page=<unavailable>, block=0x0000000001010005) at internal.h:669:10 [opt] [inlined]
    frame #2: 0x00000001000e66f4 python.exe`_mi_page_malloc(heap=0x000000087a15a790, page=0x0000023340000708, size=144, zero=false) at alloc.c:49:16 [opt] [inlined]
    frame #3: 0x00000001000e66e0 python.exe`mi_heap_malloc_small_zero(heap=0x000000087a15a790, size=144, zero=false) at alloc.c:127:19 [opt] [inlined]
    frame #4: 0x00000001000e66d0 python.exe`_mi_heap_malloc_zero_ex(heap=0x000000087a15a790, size=144, zero=false, huge_alignment=0) at alloc.c:156:12 [opt] [inlined]
    frame #5: 0x00000001000e66c8 python.exe`_mi_heap_malloc_zero(heap=0x000000087a15a790, size=144, zero=false) at alloc.c:179:10 [opt] [inlined]
    frame #6: 0x00000001000e66c8 python.exe`mi_heap_malloc(heap=0x000000087a15a790, size=144) at alloc.c:183:10 [opt] [inlined]
    frame #7: 0x00000001000e66c8 python.exe`_PyObject_MiMalloc(ctx=<unavailable>, nbytes=144) at obmalloc.c:285:12 [opt]
    frame #8: 0x0000000100103364 python.exe`_PyObject_MallocWithType(tp=0x00000233266d2c00, size=<unavailable>) at pycore_object_alloc.h:46:17 [opt] [inlined]
    frame #9: 0x0000000100103360 python.exe`_PyType_AllocNoTrack(type=0x00000233266d2c00, nitems=0) at typeobject.c:2365:19 [opt]
    frame #10: 0x000000010010327c python.exe`PyType_GenericAlloc(type=0x00000233266d2c00, nitems=<unavailable>) at typeobject.c:2396:21 [opt]
    frame #11: 0x00000001001b1218 python.exe`_PyEval_EvalFrameDefault(tstate=0x000000087a158000, frame=0x00000001051401a8, throwflag=<unavailable>) at generated_cases.c.h:1757:36 [opt]
    frame #12: 0x00000001001ae7c8 python.exe`_PyEval_EvalFrame(tstate=0x000000087a158000, frame=0x0000000105140128, throwflag=0) at pycore_ceval.h:121:16 [opt] [inlined]
    frame #13: 0x00000001001ae7b8 python.exe`_PyEval_Vector(tstate=0x000000087a158000, func=<unavailable>, locals=<unavailable>, args=<unavailable>, argcount=<unavailable>, kwnames=<unavailable>) at ceval.c:2069:12 [opt]
    frame #14: 0x0000000100061210 python.exe`_PyObject_VectorcallTstate(tstate=0x000000087a158000, callable=0x00000233269b7200, args=0x000000017feba5d8, nargsf=1, kwnames=0x0000000000000000) at pycore_call.h:169:11 [opt] [inlined]
    frame #15: 0x00000001000611e4 python.exe`method_vectorcall(method=<unavailable>, args=0x000000017febac90, nargsf=<unavailable>, kwnames=0x0000000000000000) at classobject.c:73:20 [opt]
    frame #16: 0x00000001001e1518 python.exe`_PyObject_VectorcallTstate(tstate=0x000000087a158000, callable=0x00000233400c0100, args=0x000000017febac90, nargsf=<unavailable>, kwnames=0x0000000000000000) at pycore_call.h:169:11 [opt] [inlined]
    frame #17: 0x00000001001e14e8 python.exe`context_run(self=0x000002332c3aff80, args=<unavailable>, nargs=<unavailable>, kwnames=0x0000000000000000) at context.c:728:29 [opt]
    frame #18: 0x000000010005de1c python.exe`_PyObject_VectorcallTstate(tstate=0x000000087a158000, callable=0x00000233260b5f00, args=<unavailable>, nargsf=<unavailable>, kwnames=<unavailable>) at pycore_call.h:169:11 [opt] [inlined]
    frame #19: 0x000000010005ddf4 python.exe`PyObject_Vectorcall(callable=0x00000233260b5f00, args=<unavailable>, nargsf=<unavailable>, kwnames=<unavailable>) at call.c:327:12 [opt]
    frame #20: 0x00000001001b0dcc python.exe`_PyEval_EvalFrameDefault(tstate=0x000000087a158000, frame=<unavailable>, throwflag=<unavailable>) at generated_cases.c.h:1619:35 [opt]
    frame #21: 0x00000001001ae7c8 python.exe`_PyEval_EvalFrame(tstate=0x000000087a158000, frame=0x0000000105140020, throwflag=0) at pycore_ceval.h:121:16 [opt] [inlined]
    frame #22: 0x00000001001ae7b8 python.exe`_PyEval_Vector(tstate=0x000000087a158000, func=<unavailable>, locals=<unavailable>, args=<unavailable>, argcount=<unavailable>, kwnames=<unavailable>) at ceval.c:2069:12 [opt]
    frame #23: 0x0000000100061210 python.exe`_PyObject_VectorcallTstate(tstate=0x000000087a158000, callable=0x00000233269b72c0, args=0x000000017febaee8, nargsf=1, kwnames=0x0000000000000000) at pycore_call.h:169:11 [opt] [inlined]
    frame #24: 0x00000001000611e4 python.exe`method_vectorcall(method=<unavailable>, args=0x00000001004b5370, nargsf=<unavailable>, kwnames=0x0000000000000000) at classobject.c:73:20 [opt]
    frame #25: 0x00000001002d01cc python.exe`thread_run(boot_raw=0x000000087e2b5200) at _threadmodule.c:359:21 [opt]
    frame #26: 0x0000000100252774 python.exe`pythread_wrapper(arg=<unavailable>) at thread_pthread.h:242:5 [opt]
    frame #27: 0x000000018a661c08 libsystem_pthread.dylib`_pthread_start + 136
(lldb) 
```

**Comment by kevmo314** [comment]
Thanks for reproducing, apologies for not including the stack originally.

Some more data, I am also able to get this to repro with `torch.zeros(1)` and then an object with at least nine referents. Curiously, the number of referents seems to increase the likelihood that it errors. I can still get it to fail with fewer but not nearly as consistently.

```py
import threading
import gc
import torch

class NineRefs:
    def __init__(self):
        self.a = object()
        self.b = object()
        self.c = object()
        self.d = object()
        self.e = object()
        self.f = object()
        self.g = object()
        self.h = object()
        self.i = object()

def worker(wid):
    for i in range(100):
        t = torch.zeros(1)  # Size 1 is enough
        obj = NineRefs()    # Object with 9 referents
        if i % 10 == 0:
            gc.collect()
    print(f"W{wid} done")

threads = [threading.Thread(target=worker, args=(i,)) for i in range(40)]
for t in threads: t.start()
for t in threads: t.join()
print("PASSED")
```

I suspect this explains why `cond` not being used still triggers the crash, `threading.Condition()` just happens to have enough referents to trigger the issue.

**Comment by colesbury** [comment]
Does this still occur with PyTorch nightly build?

**Comment by colesbury** [comment]
I think it's mostly likely:

1) A bug in PyTorch
2) Fixed by https://github.com/pytorch/pytorch/pull/167564

But I'm not sure what the underlying problem here is exactly and I wasn't aware of this pattern crashing.

**Comment by kevmo314** [comment]
@colesbury Wow! `2.10.0.dev20251124+cpu` does seem work! That might explain why I haven't been able to get this to work with anything except a torch tensor.

**Comment by kevmo314** [comment]
Hmm I think there is still an issue here, the application that started the investigation thread resulting in the above repro still seems to segfault randomly under load. I will try to repro this issue against the latest nightly, but this does seem to be an issue with pytorch specifically with cpython free threading.

**Comment by colesbury** [comment]
Ok, please open an issue in https://github.com/pytorch/pytorch and tag me on it
