### ISSUE TITLE
[Py3k] SyntaxError cursor shifted if multibyte character is in line.

### ISSUE THREAD

**Issue by a15f0e1c-8505-401e-a0e3-653e6d54b44d** [python/cpython#46635]
BPO | [2382](https://bugs.python.org/issue2382)
--- | :---
Nosy | @terryjreedy, @amauryfa, @abalkin, @vstinner, @ezio-melotti, @akheron, @serhiy-storchaka
Files | <li>[py3k_adjust_cursor_at_syntax_error.patch](https://bugs.python.org/file11548/py3k_adjust_cursor_at_syntax_error.patch "Uploaded as text/plain at 2008-09-21.23:04:33 by ocean-city")</li><li>[traceback_adjust_cursor.patch](https://bugs.python.org/file11670/traceback_adjust_cursor.patch "Uploaded as text/plain at 2008-09-30.23:52:05 by @amauryfa")</li><li>[py3k_adjust_cursor_at_syntax_error_v2.patch](https://bugs.python.org/file11707/py3k_adjust_cursor_at_syntax_error_v2.patch "Uploaded as text/plain at 2008-10-06.06:49:47 by ocean-city")</li><li>[issue2382.patch](https://bugs.python.org/file13354/issue2382.patch "Uploaded as text/plain at 2009-03-17.21:40:24 by @vstinner")</li><li>[unicode_utf8size.patch](https://bugs.python.org/file13356/unicode_utf8size.patch "Uploaded as text/plain at 2009-03-17.23:23:34 by @vstinner")</li><li>[unicode_width.patch](https://bugs.python.org/file13357/unicode_width.patch "Uploaded as text/plain at 2009-03-17.23:23:44 by @vstinner")</li><li>[adjust_offset.patch](https://bugs.python.org/file13358/adjust_offset.patch "Uploaded as text/plain at 2009-03-17.23:23:51 by @vstinner")</li><li>[print_exception.patch](https://bugs.python.org/file13359/print_exception.patch "Uploaded as text/plain at 2009-03-17.23:24:01 by @vstinner")</li><li>[test.py](https://bugs.python.org/file30534/test.py "Uploaded as text/plain at 2013-06-10.20:54:17 by @abalkin")</li><li>[adjust_offset_2.patch](https://bugs.python.org/file31874/adjust_offset_2.patch "Uploaded as text/plain at 2013-09-25.20:59:44 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-03-18.05:22:30.823>
labels = ['interpreter-core', 'type-bug']
title = '[Py3k] SyntaxError cursor shifted if multibyte character is in line.'
updated_at = <Date 2018-08-18.21:23:35.490>
user = 'https://bugs.python.org/ocean-city'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-18.21:23:35.490>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2008-03-18.05:22:30.823>
creator = 'ocean-city'
dependencies = []
files = ['11548', '11670', '11707', '13354', '13356', '13357', '13358', '13359', '30534', '31874']
hgrepos = []
issue_num = 2382
keywords = ['patch']
message_count = 29.0
messages = ['63895', '63904', '64156', '73539', '74106', '74114', '74119', '74129', '74148', '74149', '74361', '74362', '83636', '83659', '83700', '83712', '83714', '140377', '149960', '172500', '172525', '190933', '190934', '198419', '208115', '208697', '228027', '228034', '323734']
nosy_count = 11.0
nosy_names = ['terry.reedy', 'amaury.forgeotdarc', 'belopolsky', 'vstinner', 'ocean-city', 'LambertDW', 'ezio.melotti', 'Arfrever', 'python-dev', 'petri.lehtinen', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue2382'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
> The original problem is still present
> 
> ```
> Python 3.5.0a0 (default:5313b4c0bb6c, Sep 30 2014, 18:55:45)
> >>> A_I_U_E_O$ = None
>   File "<stdin>", line 1
>     A_I_U_E_O$ = None
>          ^
> SyntaxError: invalid syntax
> ```
> 


I think it has been fixed by now. On main (3.12) I get:

```
>>> A_I_U_E_O$ = None
  File "<stdin>", line 1
    A_I_U_E_O$ = None
             ^
SyntaxError: invalid syntax

```

**Comment by ezio-melotti** [comment]
I tried the examples in the comments above and the output look correct to me.

Note however that there are two different issues.  The first is about multibyte characters that have regular width (like `ä`) -- and that issue is fixed:
```py
>>> ä äää
  File "<stdin>", line 1
    ä äää
      ^^^
SyntaxError: invalid syntax
```

The second issue affects characters that, when *displayed*, are wider than normal (regardless of the number of bytes used to represent them):
```py
>>> Ａ＿Ｉ＿Ｕ＿Ｅ＿Ｏ＄ = None
  File "<stdin>", line 1
    Ａ＿Ｉ＿Ｕ＿Ｅ＿Ｏ＄ = None
             ^
SyntaxError: invalid character '＄' (U+FF04)
>>> print("あいうえお"$)
  File "<stdin>", line 1
    print("あいうえお"$)
                 ^
SyntaxError: invalid syntax
```
For these, the cursor is preceded by the correct amount of spaces, but since the characters are wider than usual (even with a monospace font), the output looks misaligned.

IIUC this report is about the first issue, which is now fixed, so we can close this.
I'm not sure if the second issue is something we can/should fix on Python's side.

**Comment by serhiy-storchaka** [comment]
The original error is still present.
```
>>> print "あいうえお"
  File "<stdin>", line 1
    print "あいうえお"
    ^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
This issue was not closed in 2014, because it consists of two parts, and my patch only fixed the first part. It now mostly works for many European languages (unless you use combining characters), but not for the CJK languages with double width characters and not for languages with a wide use of zero width characters.

**Comment by ezio-melotti** [comment]
If you are referring to the fact that `print "あいうえお"` is longer than `^^^^^^^^^^^^^`, is there even any way to fix this on our end?

In the example you posted, there are 13 characters and thus 13 `^` in the error message:
```py
>>> print "あいうえお"  # 13 ASCII/Hiragana characters
  File "<stdin>", line 1
    print "あいうえお"
    ^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
The alignment doesn't match simply because -- even with a monospace font -- the Hiragana character are wider than the ASCII characters.

If the `^`s are simply supposed to match the number of characters, then this is no different from:   
```py
>>> print "AIUEO"  # 13 ASCII characters
  File "<stdin>", line 1
    print "AIUEO"
    ^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

If instead we want to use a number of `^`s that aligns nicely with the Hiragana characters, then it's more complicated.

If the Hiragana characters were twice as wide we could in theory duplicate the number of `^` (even though it might be confusing to have two `^^` for a single character), but they aren't, so we can't do that:
```
01234567890123456789
あいうえおあいうえお
^^^^^^^^^^^^^^^^^^^^
```
I also suspect the exact output depends both on the available (and used) fonts, and by the rendering system (that might e.g. decide to increase the width of the ASCII characters to match the one of the widest character in the string).
So in order to produce the "right" amount of `^`s, Python will have to know the width of the string and divide it by the width of a single `^`.  In my browser, the example above would need about 16.5 `^`.

For character that actually are twice as wide or zero-width character we might in theory duplicate or remove the `^` for each such character (assuming there is a Unicode property to identify them), and the output will look right.  Currently with zero-width characters  it looks like:
```py
>>> print 'AIUEO'  # 17 ASCII/ZERO WIDTH SPACE characters
  File "<stdin>", line 1
    print 'AIUEO'
    ^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

Arguably having the number of `^` matching the number of characters -- in addition to being much easier to handle -- is also better in some situation.  In this example it hints to the fact that there are 4 extra invisible characters.

**Comment by arhadthedev** [comment]
Superseded by and fixed in gh-102310.
