### ISSUE TITLE
Missing token.COMMENT

### ISSUE THREAD

**Issue by 50f1a253-c394-40f0-b597-34b933119fba** [python/cpython#75907]
BPO | [31726](https://bugs.python.org/issue31726)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @fpom, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-26.18:21:45.867>
created_at = <Date 2017-10-08.08:08:56.554>
labels = ['type-feature', 'library']
title = 'Missing token.COMMENT'
updated_at = <Date 2021-04-26.18:21:45.866>
user = 'https://github.com/fpom'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-26.18:21:45.866>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-04-26.18:21:45.867>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2017-10-08.08:08:56.554>
creator = 'fpom'
dependencies = []
files = []
hgrepos = []
issue_num = 31726
keywords = []
message_count = 9.0
messages = ['303901', '303903', '303909', '303911', '303912', '303913', '303915', '303929', '391961']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'fpom', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31726'
versions = ['Python 2.7']
```

</p></details>

**Comment by 50f1a253-c394-40f0-b597-34b933119fba** [comment]
Module token does not have constant COMMENT. But tokenize produces it and it appears in tok_name.

**Comment by 50f1a253-c394-40f0-b597-34b933119fba** [comment]
Actually, comparing with the content of tok_name, all the following constants are missing:

```py
COMMENT = 54
NL = 55
BACKQUOTE = 56
ATEQUAL = 57
```

**Comment by bitdancer** [comment]
This is fixed in python3.  Do you have a use case for 2.7 or are you just noticing?

**Comment by 50f1a253-c394-40f0-b597-34b933119fba** [comment]
I have the problem still exists in 3.4.3 at least:

```pycon
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import token
>>> token.COMMENT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'COMMENT'
```


About the use case: I often use tokenize to build recursive descendant parsers for domain-specific languages. Not having all the token constants can be worked around with code below, but it would be so better to have a complete module...  :)

```py
import token
_tok = next(tokenize.tokenize(io.BytesIO(b"").readline))
token.tok_name[_tok.type] = "BACKQUOTE"
for number, name in token.tok_name.items() :
    if not hasattr(token, name) :
        setattr(token, name, number)
```

**Comment by serhiy-storchaka** [comment]
COMMENT and NL are added by the tokenize module. BACKQUOTE already is set, but to 25 instead of 56. ATEQUAL shouldn't be occurred in Python earlier than 3.5. How did you get your results?

**Comment by 50f1a253-c394-40f0-b597-34b933119fba** [comment]
I've just launched ipython3 (installed with pip):

```sh
$ ipython3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
```


In [1]: import token, tokenize, io

In [2]: token.BACKQUOTE
\---------------------------------------------------------------------------
```pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ebc28b79826c> in <module>()
----> 1 token.BACKQUOTE
```


AttributeError: 'module' object has no attribute 'BACKQUOTE'

In [3]: \_tok = next(tokenize.tokenize(io.BytesIO(b"").readline))

In [4]: token.tok_name[_tok.type] = "BACKQUOTE"

In [5]: for number, name in token.tok_name.items() :
   ...:     if not hasattr(token, name) :
   ...:         print(name, "=", number)
   ...:         
COMMENT = 54
NL = 55
BACKQUOTE = 56
ATEQUAL = 57
COMMENT = 58

If instead I use python3 as provided by my Linux Mint, the result is different indeed:

```pycon
$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import token, tokenize, io
>>> token.BACKQUOTE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'BACKQUOTE'
>>> _tok = next(tokenize.tokenize(io.BytesIO(b"").readline))
>>> token.tok_name[_tok.type] = "BACKQUOTE"
>>> for number, name in token.tok_name.items() :
...     if not hasattr(token, name) :
...         print(name, "=", number)
... 
COMMENT = 54
NL = 55
BACKQUOTE = 56
```

**Comment by bitdancer** [comment]
3.4 and 3.5 are in security maintenance mode only, and this is not a security bug.  This was fixed in master (3.7) as a result of bpo-25324.  The decision there was made to not backport it because no one had complained about the problem previously.  Now we have a complaint, so perhaps that decision should be revisited?

There's also Serhiy's bpo-30455.  I'm not sure if he's thinking about backporting that one or not.

And then there is the 2.7 question.  I'm not sure this is strong enough motivation to fix it there, though I wouldn't object (consistency is good).

**Comment by 50f1a253-c394-40f0-b597-34b933119fba** [comment]
Thanks for the explanation! Fixing is up to you, Python developers. But since there's a simple workaround, maybe it doesn't worth the effort.
