### ISSUE TITLE
Regression in pkgutil: iter_modules stopped taking Path argument in python 3.8.10 and 3.9.5

### ISSUE THREAD

**Issue by 7693e779-9291-4d55-9462-51c71b278ca2** [python/cpython#88227]
BPO | [44061](https://bugs.python.org/issue44061)
--- | :---
Nosy | @gpshead, @ambv, @zooba, @shreyanavigyan, @miguendes, @magul
PRs | <li>python/cpython#25964</li><li>python/cpython#26052</li><li>python/cpython#26056</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2021-05-11.23:34:04.647>
created_at = <Date 2021-05-06.17:54:01.802>
labels = ['easy', 'type-bug', '3.8', '3.9', '3.10', '3.11', 'release-blocker', 'library']
title = 'Regression in pkgutil: iter_modules stopped taking Path argument in python 3.8.10 and 3.9.5'
updated_at = <Date 2021-05-12.10:18:11.716>
user = 'https://bugs.python.org/rikardnordgren'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-12.10:18:11.716>
actor = 'lukasz.langa'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2021-05-11.23:34:04.647>
closer = 'steve.dower'
components = ['Library (Lib)']
creation = <Date 2021-05-06.17:54:01.802>
creator = 'rikard.nordgren'
dependencies = []
files = []
hgrepos = []
issue_num = 44061
keywords = ['patch', 'easy', '3.8regression', '3.9regression']
message_count = 12.0
messages = ['393120', '393128', '393130', '393132', '393133', '393135', '393147', '393154', '393168', '393478', '393494', '393498']
nosy_count = 7.0
nosy_names = ['gregory.p.smith', 'lukasz.langa', 'steve.dower', 'shreyanavigyan', 'miguendes', 'rikard.nordgren', 'magul']
pr_nums = ['25964', '26052', '26056']
priority = 'release blocker'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44061'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by dsp25no** [comment]
Issue still actual for python 3.10.4

**Comment by aniongithub** [comment]
I'm on Python 3.8.10 (Ubuntu 20.04) and still see this issue

**Comment by caleb-depotanalytics** [comment]
Same, seeing this issue on Python 3.8.10 with ubuntu

**Comment by zooba** [comment]
Yes, you'll need to get a newer version of 3.8. If Ubuntu doesn't offer one, you'll need to speak to them - we released it already, but we can't insert it into someone else's operating system.

**Comment by mpf82** [comment]
We can still see this issue in Python 3.10.11 on Red Hat

When searching https://docs.python.org/release/3.10.11/whatsnew/changelog.html#changelog there's no mention of bpo-44061

But it seems to be fixed in 3.11 - https://docs.python.org/release/3.11.2/whatsnew/changelog.html#changelog

And also in 3.8 and 3.9, but somehow 3.10 was skipped.

**Comment by zooba** [comment]
Whoops. It probably came up just as the 3.10 branch was made, and so didn't get explicitly backported to it.

I suspect a backport would be okay still, though you could also ask Red Hat to do it.

**Comment by gforcada** [comment]
(for what is worth) we are also being hit by this issue not being backported to 3.10 😕

I see that since August 2023 there has been no release of 3.10, from what I see [on the PEP 619](https://peps.python.org/pep-0619/) security releases are made "as-needed", so we don't have much chances to get this, right? 🤔

**Comment by zooba** [comment]
> we don't have much chances to get this, right?

Not from us, though it's a [one line patch](https://github.com/python/cpython/commit/0cb9775a85a051556461ea9c3089244601b7d4f8#diff-e3a5404d4dde3df6e5929e107a0433b7210a777a74edda0a9dc4c0506002b832) for your own installs (or the code that's calling into it) to use `os.fsdecode` here. Or migrating to 3.11/3.12 ought to be easy from the Python side, and will get you other benefits (I assume that since this wasn't discovered earlier that you got to 3.10 after it was already done with maintenance releases... is there a reason you didn't go straight to one of the active versions at that time?)

**Comment by gpshead** [comment]
my 2 cents: for this kind of thing when you cannot control your specific python runtime: write some code that detects if the problem is present in a given python runtime (basically a pkgutil.get_importer test case?) and use monkeypatching to hot-fix the issue if so.  due to the nature of the bugfix that _happens_ to be feasible for this one.

a functionality test case rather than a specific version check is ideal because it is fair to assume that others might also do the same and that some runtimes might have a backported patch already applied despite version numbers, etc.
