### ISSUE TITLE
'dirty' added to sys.version on Linux and Mac source builds depending on git version

### ISSUE THREAD

**Issue by 098c1aba-e677-4290-a706-0d120dde8b75** [python/cpython#88591]
BPO | [44425](https://bugs.python.org/issue44425)
--- | :---
Nosy | @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-06-15.10:27:55.893>
labels = ['type-feature', '3.7', 'build']
title = "'dirty' added to sys.version on Linux and Mac source builds depending on git version"
updated_at = <Date 2021-06-16.01:01:50.105>
user = 'https://bugs.python.org/markfinal'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-16.01:01:50.105>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-06-15.10:27:55.893>
creator = 'mark.final'
dependencies = []
files = []
hgrepos = []
issue_num = 44425
keywords = []
message_count = 1.0
messages = ['395866']
nosy_count = 2.0
nosy_names = ['ned.deily', 'mark.final']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44425'
versions = ['Python 3.7']
```

</p></details>

**Comment by StanFromIreland** [comment]
This is an upstream issue, and has been fixed for quite a few git versions now, I think this can just be closed.

**Comment by ned-deily** [comment]
As far as I can tell, this is still an issue with current versions of git (as of v2.50.1); I can still reproduce it when building outside of the cpython source directory. Looking back at forgotten history, at one time we did use the `-C $(srcdir)` option but we changed it to using `--git-dir` because the `-C` option didn't work with older versions of `git`. Either we didn't notice at the time or it's been a subsequent change in git that causes the `git describe --dirty` check to erroneously report the source repo as dirty when using the `--git-dir` approach but not with `-C`. See #74596 and #8744 for more info. I have run into this but haven't taken the time to try to track it down so thanks for the reminder!

So what to do about it: I think it should be fixed. The easiest fix would be to revert to using `-C` again in the hopes that no-one is using very old versions of git. But that's not user friendly. Rather than explicitly check the version number as was suggested in #1679, we could just add a configure test for `git -C` and, if it fails, revert to using `--git-dir`.

**Comment by vasiliyk** [comment]
As far as I can see it was fixed in git 2.21.0 (Feb 2019), [RelNotes 2.21.0](https://github.com/git/git/blob/v2.21.0/Documentation/RelNotes/2.21.0.txt) (see "git --work-tree=$there --git-dir=$here describe --dirty")

We still need to additionally pass `--work-tree`.

When we pass `--git-dir` without `--work-tree`, git treats the current directory as the working tree. Running the command from a build directory means every tracked file looks deleted, so `describe --dirty` reports dirty.

```shell
$ git --version
git version 2.54.0 (Apple Git-157)

$ git --git-dir ./cpython/.git describe --all --always --dirty
heads/main-dirty

$ git --work-tree ./cpython/ --git-dir ./cpython/.git describe --all --always --dirty
heads/main
```

Is it old enough to add `--work-tree` to `GITTAG` variable of `configure.ac` to avoid additional check?
```diff
- GITTAG="git --git-dir \$(srcdir)/.git describe --all --always --dirty"
+ GITTAG="git --work-tree \$(srcdir) --git-dir \$(srcdir)/.git describe --all --always --dirty"
```
