### ISSUE TITLE
Log emit performance degradation in RotatingFileHandlers due to filesystem checks

### ISSUE THREAD

**Issue by 3ca29b4f-3f13-46a0-8dbd-c651de0c4105** [python/cpython#90365]
BPO | [46207](https://bugs.python.org/issue46207)
--- | :---
Nosy | @vsajip
Files | <li>[logtest.py](https://bugs.python.org/file50529/logtest.py "Uploaded as text/plain at 2021-12-30.19:31:56 by dfritz"): Basic repro script</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-12-30.19:31:56.919>
labels = ['3.11', 'library', '3.9', '3.10', 'performance']
title = 'Log emit performance degradation in RotatingFileHandlers due to filesystem checks'
updated_at = <Date 2021-12-30.21:34:08.125>
user = 'https://bugs.python.org/dfritz'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-30.21:34:08.125>
actor = 'zach.ware'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-12-30.19:31:56.919>
creator = 'dfritz'
dependencies = []
files = ['50529']
hgrepos = []
issue_num = 46207
keywords = []
message_count = 1.0
messages = ['409381']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'dfritz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue46207'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by vsajip** [comment]
This should be fixed in #96159.

**Comment by serhiy-storchaka** [comment]
While the example uses TimedRotatingFileHandler, the title and the report text mention RotatingFileHandler for which the issue is still not fixed. The solution for RotatingFileHandler was provided in the duplicate #105623 issue.
