### ISSUE TITLE
Library multiprocess leaks named resources.

### ISSUE THREAD

**Issue by fd7b1cdc-b8b0-4879-9d67-bd5514f742cb** [python/cpython#90549]
BPO | [46391](https://bugs.python.org/issue46391)
--- | :---
Nosy | @pitrou, @benjaminp, @1st1, @applio, @arhadthedev, @jxdabc, @BarkingBad
PRs | <li>python/cpython#30617</li>
Files | <li>[screen.png](https://bugs.python.org/file50580/screen.png "Uploaded as image/png at 2022-01-24.09:31:44 by @jxdabc"): screenshot</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-15.18:04:57.278>
labels = ['3.8', '3.9', '3.10', 'performance', '3.11', 'library']
title = 'Library multiprocess leaks named resources.'
updated_at = <Date 2022-02-18.19:39:09.294>
user = 'https://github.com/jxdabc'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-18.19:39:09.294>
actor = 'BarkingBad'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-15.18:04:57.278>
creator = 'milestonejxd'
dependencies = []
files = ['50580']
hgrepos = []
issue_num = 46391
keywords = ['patch']
message_count = 5.0
messages = ['410654', '410657', '410853', '411456', '413504']
nosy_count = 8.0
nosy_names = ['pitrou', 'benjamin.peterson', 'sbt', 'yselivanov', 'davin', 'arhadthedev', 'milestonejxd', 'BarkingBad']
pr_nums = ['30617']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue46391'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by jxdabc** [comment]
@pitrou @benjaminp @1st1 @applio

**Comment by pitrou** [comment]
@gpshead

**Comment by PierfrancescoSoffritti** [comment]
any news on this issue?

**Comment by pchalasani** [comment]
Strangely, I see this error only when running inside PyCharm in debug mode, and it happens non-deterministically. When I run in cmd line it does not happen.

**Comment by HFrost0** [comment]
Maybe this problem is related to `spawn` method to create a new process (which is the default way in windows and macos since python 3.8). Example below works fine without warning⬇️
```
import multiprocessing as mp

mp.set_start_method('fork')  # switch to fork
global_resource = mp.Semaphore()


def submain():
    pass


if __name__ == '__main__':
    p = mp.Process(target=submain)
    p.start()
    p.join()

```

To avoid this warning in another way, create global_resource inside `if __name__ == '__main__'` to avoid re-creation in subprocess. This [question](https://stackoverflow.com/questions/14175348/why-does-pythons-multiprocessing-module-import-main-when-starting-a-new-pro) may be helpful 
```
import multiprocessing as mp


def submain():
    pass


if __name__ == '__main__':
    global_resource = mp.Semaphore()
    p = mp.Process(target=submain)
    p.start()
    p.join()

```
Test environment is macos python 3.9

**Comment by jxdabc** [comment]
@HFrost0 

Thanks for your workaround and tracking down.

Unfortunately, in the case of Google Repo. The global resource is not at the main module. Instead a module which the main module imports creates a global_resource. So, the workaround won't help in this case. : (

**Comment by jxdabc** [comment]
cc @pitrou @gpanders 
Any idea or workaround?

**Comment by stevewatanabe** [comment]
It would be nice to have this fixed....this warning appears on most of the repo commands I use :-(

**Comment by jxdabc** [comment]
> It would be nice to have this fixed....this warning appears on most of the repo commands I use :-(

me, too :-(

**Comment by pitrou** [comment]
Okay, this is fixed now. Thanks @jxdabc for the contribution!

**Comment by dturner** [comment]
Which version(s) was this fix applied to? I'm still getting this error in the latest version of Python 3.11.4 when running `repo status`

```
/Users/donturner/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by mxplusb** [comment]
This is also happening in 3.11.5

```sh
/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by gpshead** [comment]
3.10.6+ and 3.11.0+ contain PR #30617. The reproducer code listed in the opening message does not cause the Resource warning for me (including when explicitly setting the start method to 'spawn'). If you're still seeing this on recent Python versions, we need a simple way to reproduce it.

I recommend opening a new issue when you have one.

_(Just because you see this error message and find your way here does not mean that Python itself is the cause -- it can also be an application bug, we currently lack sufficient information to say one way or the other.)_
