### ISSUE TITLE
test_bdb and test_distutils fail on installed Python 3.9, 3.10 and 3.11 (setuptools 60.9.3, pip 22.0.4)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#91169]
BPO | [47013](https://bugs.python.org/issue47013)
--- | :---
Nosy | @jaraco, @vstinner, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-14.16:14:07.532>
labels = ['3.8', '3.9', '3.10', '3.11', '3.7', 'tests']
title = 'test_bdb and test_distutils fail on installed Python 3.9, 3.10 and 3.11 (setuptools 60.9.3, pip 22.0.4)'
updated_at = <Date 2022-03-16.01:15:39.379>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-16.01:15:39.379>
actor = 'jaraco'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2022-03-14.16:14:07.532>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 47013
keywords = []
message_count = 8.0
messages = ['415157', '415158', '415160', '415161', '415162', '415164', '415180', '415311']
nosy_count = 3.0
nosy_names = ['jaraco', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47013'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by jaraco** [comment]
I was able to repro at least some of the failures with this dockerfile:

```Dockerfile
FROM jaraco/multipy-tox

RUN apt install -y libarchive-tools libssl-dev
RUN wget -O - https://github.com/python/cpython/archive/refs/heads/3.9.zip | bsdtar -xf -
WORKDIR cpython-3.9
RUN sh ./configure --prefix /opt/python
RUN make install
WORKDIR /
RUN /opt/python/bin/python3 -m pip install --upgrade pip setuptools
CMD /opt/python/bin/python3 -m test
```

**Comment by jaraco** [comment]
Attempting to install a pre-release of setuptools, I find that the custom build of Python is inadequate because `_ctypes` isn't available, so `import wheel.macosx_libfile` fails. I need to figure out what dependencies are needed to get ctypes to build.

**Comment by jaraco** [comment]
My attempts to have setuptools selectively disable the distutils override worked for all of the tests except `test_bdb`. The failing test is [test_skip](https://github.com/python/cpython/blob/0ff626f210c69643d0d5afad1e6ec6511272b3ce/Lib/test/test_bdb.py#L716-L731). I suspected and then confirmed that that test fails even if the distutils patching is disabled but the Finder is still present. It seems the presence of another finder on meta_path is sufficient to break `test_bdb.StateTestCase.test_skip`.

**Comment by jaraco** [comment]
Based on this finding, I don't think there's anything that Setuptools can do short of completely removing the hook, which is a non-starter because (a) it would break all users relying on the hook to provide distutils when it's not available in the stdlib and (b) it would remove the ability for use cases still reliant on stdlib to opt out.

I suggest we'll want to find a fix for test_bdb independent of the concerns introduced by setuptools.

**Comment by jaraco** [comment]
With this Dockerfile, I can confirm the proposed fix in Setuptools has the desired effect:

```Dockerfile
FROM jaraco/multipy-tox

RUN apt install -y libarchive-tools
RUN apt install -y build-essential gdb lcov pkg-config libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev lzma lzma-dev tk-dev uuid-dev zlib1g-dev
RUN wget -O - https://github.com/python/cpython/archive/refs/heads/3.9.zip | bsdtar -xf -
WORKDIR cpython-3.9
RUN sh ./configure --prefix /opt/python
RUN make install
RUN chmod u+x /opt/python/lib/python3.9/test/ziptestdata/exe_with_*
WORKDIR /
RUN /opt/python/bin/python3 -m pip install --upgrade pip
RUN /opt/python/bin/python3 -m pip install git+https://github.com/pypa/setuptools@bugfix/3383-cpython-sensitive-tests
CMD /opt/python/bin/python3 -m test
```

```
$ docker run -it -v /Users/jaraco/p/pypa/setuptools:/src @$(docker build -q .) /opt/python/bin/py
thon3 -m test test_importlib test_distutils test_peg_generator
0:00:00 load avg: 0.11 Run tests sequentially
0:00:00 load avg: 0.11 [1/3] test_importlib
0:00:01 load avg: 0.11 [2/3] test_distutils
/opt/python/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
0:00:02 load avg: 0.11 [3/3] test_peg_generator
/opt/python/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

== Tests result: SUCCESS ==

All 3 tests OK.

Total duration: 3.0 sec
Tests result: SUCCESS
```

Unfortunately, it also creates its own regression in `test_venv`:

```
$ docker run -it -v /Users/jaraco/p/pypa/setuptools:/src @$(docker build -q .) /opt/python/bin/py
thon3 -m test test_venv
0:00:00 load avg: 0.04 Run tests sequentially
0:00:00 load avg: 0.04 [1/1] test_venv
test test_venv failed -- Traceback (most recent call last):
  File "/opt/python/lib/python3.9/test/test_venv.py", line 544, in test_with_pip
    self.do_test_with_pip(True)
  File "/opt/python/lib/python3.9/test/test_venv.py", line 511, in do_test_with_pip
    out, err = check_output([envpy,
  File "/opt/python/lib/python3.9/test/test_venv.py", line 44, in check_output
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/tmp/tmpqts0cln1/bin/python3', '-W', 'ignore::DeprecationWarning', '-I', '-m', 'ensurepip._uninstall']' returned non-zero exit status 1.

test_venv failed (1 error)

== Tests result: FAILURE ==

1 test failed:
    test_venv

Total duration: 5.7 sec
Tests result: FAILURE
```

And annoyingly, that error message is all but worthless for diagnosis.

**Comment by jaraco** [comment]
After adding a breakpoint where the error is occurring (pytest would do this automatically with `--pdb`), I'm able to inspect the error:

```
(Pdb) print(exc.stderr.decode())
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/opt/python/lib/python3.9/runpy.py", line 221, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/opt/python/lib/python3.9/runpy.py", line 130, in _get_module_details
    spec = importlib.util.find_spec(mod_name)
  File "/opt/python/lib/python3.9/importlib/util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/tmp/tmpntevhrty/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 79, in find_spec
    return method()
  File "/tmp/tmpntevhrty/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 100, in spec_for_pip
    if self.pip_imported_during_build():
  File "/tmp/tmpntevhrty/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 111, in pip_imported_during_build
    return any(
  File "/tmp/tmpntevhrty/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 112, in <genexpr>
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/python/lib/python3.9/ensurepip/_uninstall.py", line 31, in <module>
    sys.exit(_main())
  File "/opt/python/lib/python3.9/ensurepip/_uninstall.py", line 27, in _main
    return ensurepip._uninstall_helper(verbosity=args.verbosity)
  File "/opt/python/lib/python3.9/ensurepip/__init__.py", line 152, in _uninstall_helper
    return _run_pip(args + [p[0] for p in reversed(_PROJECTS)])
  File "/opt/python/lib/python3.9/ensurepip/__init__.py", line 34, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/opt/python/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmpntevhrty/bin/python3', '-c', '\nimport runpy\nimport sys\nsys.path = [] + sys.path\nsys.argv[1:] = [\'uninstall\', \'-y\', \'--disable-pip-version-check\', \'pip\', \'setuptools\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
```

It seems there's a new issue, probably brought on by changes in Setuptools.

**Comment by jaraco** [comment]
The failure looks suspiciously similar to pypa/setuptools#2940.

**Comment by jaraco** [comment]
Okay, so Setuptools fixed that issue and released it in 60.0.3, but the version of Setuptools installed into the virtualenv doesn't have that fix. But that doesn't explain why the issue only emerges when the version of Setuptools is bumped.

Aah. I get it. This test is running a venv with `--system-site-packages`, so the `distutils-precedence.pth` for the system site packages is taking effect, enabling `SETUPTOOLS_USE_DISTUTILS=local`, but then because the venv gets an old version of Setuptools with the bug in it, that version gets invoked. This bug will go away when the version of Setuptools installed into the venvs is updated.

**Comment by jaraco** [comment]
At this point, pypa/setuptools#3386 (to be released with Setuptools>=62.5.0) and gh-93962 should fix the issue.

**Comment by yilun11** [comment]
@jaraco I upgraded to setuptools 64.0.3 and still get these errors. Is there a solution?

Using docker pull registry.gitlab.com/python-devs/ci-images:active from README for dev container
python3 -m test test_importlib test_distutils test_peg_generator

All 3 tests fail due to no module found. Pip install --upgrade setuptools doesn't resolve although version is 64.0.3. I also tried make from source and it throws the error at test_peg_generator.

Thanks!

**Comment by jaraco** [comment]
@yilun11 I suspect your issue is different than this one. I can indeed produce an error if I use your repro:

```
 ~ $ docker run -it registry.gitlab.com/python-devs/ci-images:active python3 -m test test_importlib | grep ModuleNotFound
ModuleNotFoundError: No module named 'test.test_importlib'
```

However, I also observe that I get the same error for any test module:

```
 ~ $ docker run -it registry.gitlab.com/python-devs/ci-images:active python3 -m test test_bool | grep ModuleNotFound
ModuleNotFoundError: No module named 'test.test_bool'
```

When I look at the Python lib directory, I see a `support` subpackage, but no modules for the tests themselves. I suspect the image you're using simply doesn't have the Python tests installed, so you shouldn't expect it to work. The `ModuleNotFoundError` is a fairly generic error not specific to this issue. This issue is specific to a few select modules not working when Setuptools is present. You can tell if you're affected by the issue if you can work around it by setting `SETUPTOOLS_USE_DISTUTILS=stdlib`.

To close the loop on this issue, I've confirmed that the repro that previously failed no longer fails with the latest Setuptools:

```
 draft $ cat Dockerfile
FROM jaraco/multipy-tox

RUN apt install -y libarchive-tools
RUN apt install -y build-essential gdb lcov pkg-config libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev lzma lzma-dev tk-dev uuid-dev zlib1g-dev
RUN wget -O - https://github.com/python/cpython/archive/refs/heads/3.9.zip | bsdtar -xf -
WORKDIR cpython-3.9
RUN sh ./configure --prefix /opt/python
RUN make install
RUN chmod u+x /opt/python/lib/python3.9/test/ziptestdata/exe_with_*
WORKDIR /
RUN /opt/python/bin/python3 -m pip install --upgrade pip setuptools
CMD /opt/python/bin/python3 -m test
 draft $ docker run -it @$(docker build -q .) /opt/python/bin/python3 -m test test_importlib test_distutils test_peg_generator
0:00:00 load avg: 0.63 Run tests sequentially
0:00:00 load avg: 0.63 [1/3] test_importlib
0:00:01 load avg: 0.63 [2/3] test_distutils
/opt/python/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
0:00:02 load avg: 0.66 [3/3] test_peg_generator
/opt/python/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

== Tests result: SUCCESS ==

All 3 tests OK.

Total duration: 2.9 sec
Tests result: SUCCESS
```
