### ISSUE TITLE
Crash with an evil custom `mro()` on a metaclass

### ISSUE THREAD

**Issue by izbyshev** [python/cpython#92112]
**Crash report**

There is a path in `type_mro_modified` that results in double-free of `*mro_meth`:
* https://github.com/python/cpython/blob/ad5e8520f3e117f45481513014548a39879d30d2/Objects/typeobject.c#L362
* https://github.com/python/cpython/blob/ad5e8520f3e117f45481513014548a39879d30d2/Objects/typeobject.c#L371

A reproducer:
```
class B:
    pass

class M(type):
    def mro(cls):
        del M.mro
        return (B,)

class C(metaclass=M):
    pass
```

Crash with the debug CPython:
```
$ ./python mro-crasher.py
/home/test/cpython/Include/object.h:601: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x7f88c12d1a90 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x00007f88c13cb080 (most recent call first):
  File "/home/test/mro-crasher.py", line 9 in <module>
Aborted (core dumped)
```

This bug was introduced in #73052.

**Comment by izbyshev** [comment]
I'll open a PR shortly.

**Comment by izbyshev** [comment]
Opened #92113. @JulienPalard

**Comment by JulienPalard** [comment]
Fixed by @izbyshev in https://github.com/python/cpython/pull/92113 (Thank you!).

**Comment by ctismer** [comment]
@izbyshev Thanks a lot for fixing this! We had problems with PySide and type creation and did a crude work-around.
The error is gone since Python 3.9.13.
Unfortunately, the same error is still in Python 3.8 (which we hopefully deprecate soon).
Is it ok if I re-open it?

**Comment by JelleZijlstra** [comment]
3.8 is in security fix-only mode, so we probably won't fix this.

**Comment by ctismer** [comment]
Ok, I understand. Closing the issue, again. Thanks
