### ISSUE TITLE
`_abc._abc_subclasscheck` has very poor performance and (I think) a memory leak

### ISSUE THREAD

**Issue by samuelcolvin** [python/cpython#92810]
**Bug report**

I'm been hunting a memory leak in pydantic and I keep seeing `_abc_subclasscheck` popping up in the memray flamegraph.

Locally I've seen memray report that `_abc_subclasscheck` is using 2.8GB of memory in some cases!

I can't get anything that bad in a minimal example, but I have the following:

```py
from abc import ABCMeta
from datetime import datetime


class MyMetaclass(ABCMeta):
    pass


class MyClass(metaclass=MyMetaclass):
    pass


def main():
    class Foobar(MyClass):
        pass

    assert issubclass(Foobar, MyClass)
    assert not issubclass(int, MyClass)
    assert not issubclass(str, MyClass)
    assert not issubclass(datetime, MyClass)
    t = type('A', (), {})
    assert not issubclass(t, MyClass)


if __name__ == '__main__':
    import os, psutil
    process = psutil.Process(os.getpid())
    mb = 1024 * 1024
    last = 0
    for i in range(5_000):
        main()
        # mem = process.memory_info().rss
        # print(f'{i + 1:>4d} {mem / mb:8.2f}MB {(mem - last) / mb:+8.2f}MB | {"━" * int(mem / 8_000_000)}')
        # last = mem
```

A few things to note:
* the commented out last few lines print current memory and change in memory over time
* I'm not sure exactly which `issubclass` calls are necessary, certainly I don't see a rise in memory with just the last one
* some memory drops (presumably related to clearing the abc caches?) is happening, but overall memory is increasing
* The performance of `issubclass` on an abc is very poor indeed - this script takes 14seconds, if i switch `ABCMeta` to `type` it takes 121ms!

**Your environment**

* Python 3.10.0 installed with venv
* Ubuntu 21.10

### Linked PRs
* gh-131914
* gh-141171
* gh-144941

**Comment by sweeneyde** [comment]
From what I can gather, there is no actual *leak* strictly speaking, but it seems like it might be a corner case where that garbage collector isn't running as often as it maybe should be for this scenario.

Doing something like below shows some strange artifacts where the "before collection" case has widely variable numbers of `weakref.weakref` objects lingering around, and widely variable performance. However, calling `gc.collect()` consistently takes the number back down. Does manually adding `collect()` calls fix your use-case?

```python
from abc import ABCMeta
from gc import collect, get_objects
from collections import Counter
from pprint import pprint

class MyMetaclass(ABCMeta):
    pass

class MyClass(metaclass=MyMetaclass):
    pass

def main():
    class Sub(MyClass):
        pass
    assert issubclass(Sub, MyClass)

    class Other:
        pass
    assert not issubclass(Other, MyClass)

def print_object_types(n=5):
    types = Counter(map(type, get_objects())).most_common(n)
    pprint(types, underscore_numbers=True)

N = 1000

for _ in range(1000):
    N += N//10
    for j in range(N):
        main()
    print(N)
    print("before collection:")
    print_object_types()
    while collect():
        pass
    print("after collection:")
    print_object_types()
    print("\n\n")
```

@pablogsal any ideas?

**Comment by pablogsal** [comment]
I will investigate later but you can also try to adjust the gc threshold down to force collections more often and another thing is to set the GC flags to debug flags to gc.DEBUG_SAVEALL so the cycles are being saved so we can inspect what objects are responsible or the memory and why they are forming cycles.

**Comment by samuelcolvin** [comment]
Rather than the GC, and since the problem seems to be more severe when the checks return false, I thought this might be `_abc_negative_cache` growing indefinitely?

**Comment by pablogsal** [comment]
> Rather than the GC, and since the problem seems to be more severe when the checks return false, I thought this might be `_abc_negative_cache` growing indefinitely?

Is possible, but we need some analysis and unfortunately I am writing this from my phone while hiking so I cannot test until I am back at home :sweat_smile: 

I would be surprised if this is a GC problem to be honest because that would involve some circular references and unless I am missing something there should not be growing isolated cycles here.

**Comment by pablogsal** [comment]
My educated guess is that is likely this:

https://github.com/python/cpython/blob/36d42e701f8a4040e7daf70138217038bfde3c78/Modules/_abc.c#L201

**Comment by sweeneyde** [comment]
I notice that the pure-python version uses a `WeakSet` where the c version uses a set of weakrefs.

https://github.com/python/cpython/blob/953ab0795243900ccccaaca069d932730a86fc20/Lib/_py_abc.py#L50

**Comment by pablogsal** [comment]
I asked a college to run the `memray` flamegraphs with native introspection.

# Leaks (the memory that is there **at the end of execution**

![leaks](https://user-images.githubusercontent.com/11718525/168490305-d046a952-1d32-47ec-8ca7-82a69c39d1cd.png)
)

# Peak (the chunks that form the heap when the memory is at its peak)

![peak](https://user-images.githubusercontent.com/11718525/168490341-0af23b9c-bfe2-4dd7-ace5-22501313e5b7.png)

# Resident size over time

![plot](https://user-images.githubusercontent.com/11718525/168490371-0308a402-9b1b-4129-8ff8-20876970ca85.png)

You can see in the last plot how the cache is periodically cleaned up (maybe because GC passes?), but there is *something* that survives.

**Comment by zrothberg** [comment]
So I messed around with python version of this a bit. By just removing the negative cache from ABCMeta it become around 30x faster and no longer had a memory leak taking 2 second to do 10000 iterations. Even manually calling gc.collect seems to be unable to free up all the memory. 

It grows from 11mb at startup to 68 MB on end. 

I went further and swapped to a regular ```set()``` this had a memory leak but it was actually about half the size of the original memory leak and only went up to 33mb. 

VERY VERY VERY strangely adding that to ```__subclasscheck__``` right before setting the cache actually speeds up the program about 3 times. 

```py
if cls.__name__=="Foobar":
    pass
else:
    print(f"{cls.__name__} has {len(cls.__subclasses__())} subclasses")
```

My best guess is the issue is just one of pure volume. 

https://github.com/python/cpython/blob/733e15f1707ddec502a69c8c324c77e02ca11fa9/Lib/_py_abc.py#L141-L147

Because you are recursively running instance check and recursively caching the values its just creating a ton of items in the WeakRefs. Bumping the original code up to two child classes from MyClass grinds to an absolute halt. The real issue is if there is ever a parent class that has many children (like every single item in pydantic) you are going to perform subclass checking on 100+ different child classes and are going to be caching values in all 100+ different child classes. Because gc isn't able to catch up during this Myclass ends up with a few thousand subclasses still attached to it each of which is recursively gone through. Manually calling gc cleared the weakreferences from the ```__subclasses__``` method but the leaked memory does not recover

Further it is actually bugged and doesn't work properly which is actually what is stopping this from melting down all the time. If a class was already called with ```isinstance``` when its called a second time it will never run through all the subclasses as the cache will not break and it will be short circuited at the top. Frankly that bug probably prevented a lot of major issues. 

https://github.com/python/cpython/blob/733e15f1707ddec502a69c8c324c77e02ca11fa9/Lib/_py_abc.py#L115-L121

The cache is never invalidated for subclassing just for registrations. 

@samuelcolvin For pydantic I would just replace the __subclasscheck__ on the metaclass for the main pydanitc metaclass. This should clear up the bulk of the memory leak as well as likely pretty dramatically increase the actual speed since I doubt it needs to check every single child class on a miss. I would presume it in fact should never need to because all child classes directly descended from the BaseClass.

**Comment by corona10** [comment]
The ratio of cache hit/miss looks super low for this scenario, can we switch caches into LRUCache?

**Comment by zrothberg** [comment]
I honestly dont think it will fix the core issue. The main problem is just the way it walks down the class tree. This makes any sufficiently large class hierarchy impossibly slow and causes massive memory consumption. Switching to an LRU cache only solves the memory part but the above example of 10k comparisons still takes 2 mins to run on my macbook because it causes 10k lookups per issubclass call. 

If you are generating classes the bulk of which never get compared in any natural way them getting involved in their parents issubclass call is unintuitive at best. Frankly I am not sure I fully understand the intent of it. I presume its for registered calls but if it is not and the intent is to allow subclasses to specialize how they check then it should just be considered bugged.

**Comment by iritkatriel** [comment]
See also https://github.com/python/cpython/issues/94284.

**Comment by Viicos** [comment]
If it can help, seems like creating a subclass of `MyClass` before each `issubclass` call is necessary to reproduce:

```python
from abc import ABCMeta


class MyMetaclass(ABCMeta):
    pass


class MyClass(metaclass=MyMetaclass):
    pass

def main():
    class Foobar(MyClass):
        pass

    class A:
        pass

    assert not issubclass(A, MyClass)


for i in range(5_000):
    main()
```

**Comment by pablogsal** [comment]
Here is the flamegraph I get with memray and the script provided by @Viicos:

```
$ memray run --native --trace-python-allocators lel.py
$ python -m memray flamegraph memray-lel.py.1917106.bin --leaks -f
```
![memray](https://github.com/user-attachments/assets/ea0a1b6c-27d1-4bbe-a54b-d4dc30400c20)

**Comment by pablogsal** [comment]
Looks like is this call: https://github.com/python/cpython/blob/3d7b5b369a2c05efb033811b25f35d767d87769d/Modules/_abc.c#L794

**Comment by pablogsal** [comment]
Hummm, it 

> Thanks [@pablogsal](https://github.com/pablogsal), yes the negative cache seems to be properly gc'd. I experimented a bit more and it seems that it takes longer and longer as you iterate in the example code.
> 
> from abc import ABCMeta, _get_dump
> 
> 
> class MyMetaclass(ABCMeta):
>     pass
> 
> 
> class MyClass(metaclass=MyMetaclass):
>     pass
> 
> def main():
>     class Foobar(MyClass):
>         pass
> 
>     class A:
>         pass
> 
>     assert not issubclass(A, MyClass)
> 
> N = 10_000
> 
> for i in range(N):
>     if (i % 100) == 0:
>         print(f"Iteration {i}")
>         mycls_registry, mycls_cache, mycls_negative_cache, _ = _get_dump(MyClass)
>         print(f"{len(mycls_registry)=}")
>         print(f"{len(mycls_cache)=}")
>         print(f"{len(mycls_negative_cache)=}")
>     main()
> With the following code, we notice three things:
> 
> * the caches/registry are not growing over time
> * as time goes by, it takes longer and longer to iterate over the loop (it takes around 1s to iterate a hundred times when you reach ~7000 -- on my machine)
> * Depending on the run, you may notice a speedup when reaching some iteration, like it's starting over. The memray graph also shows a drop in memory usage, similarly to the ones shown [here](https://github.com/python/cpython/issues/92810#issuecomment-1127004123). Most of the time though, this speedup doesn't happen.
> 
> I checked the above code with `py-spy`:
> 
> * Python: 3.10 (I get `py-spy` errors on 3.13 when running in native mode)
> * command: `py-spy record -f speedscope -o repro.json --native -- python repro.py`
> * file: [repro.json](https://github.com/user-attachments/files/18147736/repro.json). Check with: https://www.speedscope.app/
> 
> This is what I get in left heavy mode:
> 
> ![image](https://github.com/user-attachments/assets/cd7702ea-b73b-4eae-a456-aa36fb57aeff)

This seems to suggest that is just the GC passes to traverse those objects no?

**Comment by peterchenadded** [comment]
Are there plans to fix this? We ended up not use ABC and @abstract method for this reason.

**Comment by Viicos** [comment]
> For pydantic we ended up overriding the `ModelMetaclass.__instancecheck__` to just check against the `instance.__class__.__mro__` without any caching and seems to work well for us.

Note that we already implemented such workarounds in Pydantic, so it might not be necessary for you to do so.

**Comment by peterchenadded** [comment]
@Viicos is that so? What version I tested on 2.10.6 and the issue was still happening.

**Comment by Viicos** [comment]
Yes because `__instancecheck__` was actually the wrong method to override. This was fixed by https://github.com/pydantic/pydantic/pull/11116 in 2.11.

**Comment by peterchenadded** [comment]
Thanks, is that available in pydantic 2.11.0b2 I can pull it down to give it a test. 

But looking at the code I am not sure it fixes the issue since it first checks if it's a pydantic decorated class and then does the check anyway?

Removing the cache seems to give significant memory improvement with memory I could see our memory usage was 10gb and down to 1.5gb after removing the cache.

**Comment by peterchenadded** [comment]
Yep confirmed the code is in pydantic 2.11.0b2, will try and see. Though I am not really sure it's meaningful because what if I start using pydantic decorator?

**Comment by peterchenadded** [comment]
@Viicos, no it doesn't fix the issue. 

The memory usage was still 10gb and performance was very similar to pydantic 2.7.

To fully fix my issue I needed to

1. Remove all usage of ABC and abstract method - I just changed them to throw NotImplementedError

Yes we had non pydantic classes that use ABC

3. Override `_model_construction.ModelMetaclass.__instancecheck__` as below:

```python
def __instancecheck__(self, instance: Any) -> bool:
    """Override ABC logic to disable caching causing memory and performance issues."""
    if not hasattr(instance, '__pydantic_validator'):
        return False
    return self in instance.__class__.__mro__
```

3. Your right we would have to do something similar with issubclass - thanks for pointing this out, it wasn't a performance concern for us

**Comment by Viicos** [comment]
Please open an issue on the Pydantic issue tracker with a MRE as we are discussing workarounds and not the issue per se.

**Comment by peterchenadded** [comment]
Thanks @Viicos, though this is definitely an abc issue not pydantic, which is why the issue was raised here in the first place. We are just seeing the side effect of it in pydantic.

Are we planning to work around it in pydantic if so I can raise a MRE.

**Comment by Viicos** [comment]
I took a deeper look (at the `_py_abc` implementation but I assume it is equivalent to the C impl) and came to the same conclusions as @zrothberg. In https://github.com/python/cpython/issues/92810#issuecomment-1166589468:

> If you are generating classes the bulk of which never get compared in any natural way them getting involved in their parents issubclass call is unintuitive at best. Frankly I am not sure I fully understand the intent of it. I presume its for registered calls but if it is not and the intent is to allow subclasses to specialize how they check then it should just be considered bugged.

It seems that while the current `_py_abc.ABCMeta.__subclasscheck__` implementation is inefficient with a lot of subclasses it is necessary. Looking at it step by step (ignoring the cache related logic):

- This is equivalent to an `issubclass(subclass, cls)` check without virtual classes involved:

    https://github.com/python/cpython/blob/00f0771e4dbd8c8b66b302ebc16bb21f5d46b304/Lib/_py_abc.py#L131-L134

- This:

    https://github.com/python/cpython/blob/00f0771e4dbd8c8b66b302ebc16bb21f5d46b304/Lib/_py_abc.py#L135-L139

    is necessary to support:

    ```python
    from abc import ABC

    class MyABC(ABC): ...

    class Test: ...

    MyABC.register(Test)

    issubclass(Test, MyABC)  # True
    ```

- This:

    https://github.com/python/cpython/blob/00f0771e4dbd8c8b66b302ebc16bb21f5d46b304/Lib/_py_abc.py#L140-L144

    is necessary (and is the source of the performance issues) to support:

    ```python
    from abc import ABC


    class MyABC(ABC): ...


    class MySubABC(MyABC, ABC): ...


    class Test: ...


    MySubABC.register(Test)

    issubclass(Test, MyABC)  # True
    ```

The last one seems really uncommon. So I think the only solution would be to try to optimize things while keeping the existing logic, which seems relatively hard.

What I propose instead would be a way to disable virtual subclasses, e.g. with a metaclass argument:

```python
class MyABC(metaclass=ABCMeta, allow_virtual_subclasses=False):  # default True, name TBD
    pass
```

If `allow_virtual_subclasses` is `True`, `ABCMeta.__subclasscheck__` essentially acts as a simple `cls in subclass.__mro__` check.

**Comment by dolfinus** [comment]
## The cause

Here is slightly altered reproducer from https://github.com/pydantic/pydantic/issues/11605:
<details>
<summary>test_performance_abc.py</summary>

```python
from abc import ABCMeta
# from _py_abc import ABCMeta
import time

class Root(metaclass=ABCMeta):
    pass

class Class1(Root):
    pass

class Class2(Root):
    pass


def _create_subclass1():
    class NestedClass1(Class1):
        pass

    return NestedClass1


def _create_subclass2():
    class NestedClass2(Class2):
        pass

    return NestedClass2

def test_performance():
    print("Creating new objects to check")
    objects = []
    for i in range(6000):
        if i % 2 == 0:
            objects.append(_create_subclass1()())
        else:
            objects.append(_create_subclass2()())

    print("Created len(objects) = ", len(objects))

    print("Started compairing objects")
    for_root_ns = 0
    for_class1_ns = 0
    for_class2_ns = 0
    for m in objects:
        start = time.perf_counter_ns()
        isinstance(m, Root)
        for_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        isinstance(m, Class1)
        for_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        isinstance(m, Class2)
        for_class2_ns += time.perf_counter_ns() - start

    print("Completed compairing classes")
    print("isinstance(Root), seconds:", for_root_ns / 1_000_000_000)
    print("isinstance(Class1), seconds:", for_class1_ns / 1_000_000_000)
    print("isinstance(Class2), seconds:", for_class2_ns / 1_000_000_000)


if __name__ == "__main__":
    test_performance()
```

```
Creating new objects to check
Created len(objects) =  6000
Started compairing objects
Completed compairing classes
isinstance(Root), seconds: 0.110785353
isinstance(Class1), seconds: 95.666855296
isinstance(Class2), seconds: 105.506494938
```

[memray-flamegraph-test_performance_abc.py.1337997.tar.gz](https://github.com/user-attachments/files/19526996/memray-flamegraph-test_performance_abc.py.1337997.tar.gz)

</details>

It creates the following class tree:
```
Root(ABC)
|
|- Class1
|\
| |- NestedClass1_1
| |- NestedClass1_2
| |- ...
| \- NestedClass1_3000
|
|- Class2
 \
  |- NestedClass2_1
  |- NestedClass2_2
  |- ...
  \- NestedClass2_3000

```

compairing classes which are a direct descendants or ancestors, like:
```python
issubclass(Class1, Root)
issubclass(Class2, Root)
issubclass(NestedClass1_1, Class1)
issubclass(NestedClass2_1, Class2)
issubclass(NestedClass1_1, Root)
issubclass(NestedClass2_1, Root)
```
takes very little time, as parent class already in `__mro__` of its subclass, and `True` is returned early:
https://github.com/python/cpython/blob/v3.13.2/Lib/_py_abc.py#L132-L134
https://github.com/python/cpython/blob/v3.13.2/Modules/_abc.c#L784-L791

But compairing classes which are not related to each other, like:
```python
issubclass(NestedClass2_1, Class1)
```
takes a lot of time, because this clause:
https://github.com/python/cpython/blob/v3.13.2/Lib/_py_abc.py#L141-L144
https://github.com/python/cpython/blob/v3.13.2/Modules/_abc.c#L800-L825
leads to compairing each class in inheritance tree with another class in this tree:
```
issubclass(NestedClass2_1, Class1)
issubclass(NestedClass2_2, Class1)
issubclass(NestedClass2_3, Class1)
...
issubclass(NestedClass2_6000, Class1)

issubclass(NestedClass2_1, NestedClass2_1)
issubclass(NestedClass2_2, NestedClass2_1)
...
issubclass(NestedClass2_6000, NestedClass2_1)

....
```
This is effectively O(N^2) algorithm, where N is number of classes under ABCMeta (and all their children). For 6K classes it takes ~25 seconds.
Worse than time complexity is the fact that all these checks add entries to `cls._abc_cache` and `cls._abc_negative_cache`, taking up a lot of RAM. Script above consumes ~3.6GB of RAM.

Getting rid of ABC from inheritance tree:
<details>
<summary>test_performance_no_abc.py</summary>

```python
import time

class Root:  # no ABCMeta
    pass

class Class1(Root):
    pass

class Class2(Root):
    pass


def _create_subclass1():
    class NestedClass1(Class1):
        pass

    return NestedClass1


def _create_subclass2():
    class NestedClass2(Class2):
        pass

    return NestedClass2

def test_performance():
    print("Creating new objects to check")
    objects = []
    for i in range(6000):
        if i % 2 == 0:
            objects.append(_create_subclass1()())
        else:
            objects.append(_create_subclass2()())

    print("Created len(objects) = ", len(objects))

    print("Started compairing objects")
    for_root_ns = 0
    for_class1_ns = 0
    for_class2_ns = 0
    for m in objects:
        start = time.perf_counter_ns()
        isinstance(m, Root)
        for_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        isinstance(m, Class1)
        for_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        isinstance(m, Class2)
        for_class2_ns += time.perf_counter_ns() - start

    print("Completed compairing classes")
    print("isinstance(Root), seconds:", for_root_ns / 1_000_000_000)
    print("isinstance(Class1), seconds:", for_class1_ns / 1_000_000_000)
    print("isinstance(Class2), seconds:", for_class2_ns / 1_000_000_000)


if __name__ == "__main__":
    test_performance()
```
</details>

Reduces time to 0.02 seconds and very little RAM.
```
Creating new objects to check
Created len(objects) =  6000
Started compairing objects
Completed compairing classes
isinstance(Root), seconds: 0.02807116
isinstance(Class1), seconds: 0.030564255
isinstance(Class2), seconds: 0.0326596
```

[memray-flamegraph-test_performance_no_abc.py.1337451.tar.gz](https://github.com/user-attachments/files/19526998/memray-flamegraph-test_performance_no_abc.py.1337451.tar.gz)

## Possible solution

As mentioned before, getting rid of this `for` loop drastically improves both time and RAM usage:
```
for scls in cls.__subclasses__():
  ...
```

Results are just the same for `Root(metaclass=ABCMeta)` and `Root()`:
```
Creating new objects to check
Created len(objects) =  6000
Started compairing objects
Completed compairing classes
isinstance(Root), seconds: 0.010256801
isinstance(Class1), seconds: 0.008510441
isinstance(Class2), seconds: 0.007868972
```

It is possible to prevent breaking code like this

<details>

```python
from abc import ABC

class Root(ABC): ...

class Class1(Root): ...

class Other: ...

Class1.register(Other)

assert issubclass(Other, Class1) is True
assert issubclass(Other, Root) is True  # fails without cls.__subclasses__()
```
</details>

by introducing fix to class registration mechanism:
<details>

```python
Class1.register(Other)
Root.register(Other)  # call .register() for each parent in inheritance tree

assert issubclass(Other, Class1) is True
assert issubclass(Other, Root) is True
```
</details>

I've implemented it here: #131914.

## Caveats 

Solution above breaks code like:
```
from abc import ABC

class Root(ABC): ...

class Class1(Root):
  __subclasses__ = lambda: [Other]

class Other: ...

assert issubclass(Other, Class1) is True
assert issubclass(Other, Root) is True  # fails without cls.__subclasses__()
```
because `cls.__subclasses__()` calls are important here to get all class descendants.

Probably, introducing some mechanism for resolving only these `__subclasses__ = ...` usage without iterating over the entire inheritance tree could solve this as well.

**Comment by dolfinus** [comment]
BTW, I'm not sure that `__subclases__ = ...` override should be checked by `isinstance` or `issubclass` at all.

For example, this is not the case for non-ABC classes:
```python
class Root: ...

class Class1(Root):
  __subclasses__ = lambda: [Other]

class Other: ...

assert Root.__subclasses__() == [Class1]
assert Class1.__subclasses__() == [Other]

assert issubclass(Class1, Root) is True
assert issubclass(Other, Class1) is False
assert issubclass(Other, Root) is False
```
So why should it be default for ABCMeta?

Github code search doesn't return any combination of `__subclasses__` with ABC/ABCMeta. Only custom metaclasses where `__subclasses__` is tracked manually:
https://github.com/search?q=language%3APython+%22__subclasses__+%3D%22&type=code&p=1

**Comment by peterchenadded** [comment]
@dolfinus great idea to update the register to push the data to the right place to avoid the last expensive subclasses loop in https://github.com/python/cpython/pull/131914.  Note you can avoid the first entry from __mro__ since that's going to be the class you already registered. Not that it really matter in terms of performance.

**Comment by dolfinus** [comment]
Well, it looks like recursive subclass check cannot be eliminated for now.

Introducing recursive `.register()` calls (bubbling it up to the root class) allows for check like this without iterating over `cls.__subclasses__()`:
```python
from abc import ABC

class Root(ABC):
  pass

class Direct(Root):
  pass

class Registrant:
  pass

Direct.register(Registrant)

assert issubclass(Registrant, Root)
```

But it breaks at weird cases like:

```python
from abc import ABC

class Root(ABC):
  pass

class Direct(Root):
  @classmethod
  def __subclasses__(cls):
    return [Indirect]

class Indirect:
  pass

assert issubclass(Indirect, Root)
```
As `__subclasses__` can be overridden at any level of ABCMeta inheritance tree, adding conditions like this:
```python
for scls in cls.__subclasses__():
  scls_dict = getattr(scls, "__dict__", {})
  if "__subclasses__" not in scls_dict and "__subclasscheck__" not in scls_dict:
    continue
  if issubclass(scls, target):
    ...
```
will prevent `issubclass(Indirect, Root)` from calling `issubclass(Indirect, Direct)`, and assert will fail.

**Comment by dolfinus** [comment]
I was able to add [a workaround](https://github.com/python/cpython/pull/131914#discussion_r2052264731) to this method to avoid adding the same class to cache/negative_cache of all of all children of Root. and this reduced memory usage a lot.
<details>
<summary>test_performance_abc.py</summary>

```python
#from abc import ABCMeta
from _py_abc import ABCMeta
import time
import psutil
import os

NS_PER_SECOND = 1_000_000_000

class Root(metaclass=ABCMeta):
    pass

class Class1(Root):
    pass

class Class2(Root):
    pass

class Class3(Root):
    pass

class Class4(Root):
    subclasses = []
    @classmethod
    def __subclasses__(cls):
        return cls.subclasses


def _create_subclass1():
    class NestedClass1(Class1):
        pass

    return NestedClass1


def _create_subclass2():
    class NestedClass2(Class2):
        pass

    return NestedClass2


def _create_subclass3():
    class NestedClass3:
        pass

    return NestedClass3


def _create_subclass4():
    class NestedClass4:
        pass

    Class4.subclasses.append(NestedClass4)

    return NestedClass4


def test_performance():
    iters = 2000
    print("Creating new classes to check")
    objects_subclass1 = []
    for i in range(iters):
        subclass1 = _create_subclass1()
        objects_subclass1.append(subclass1())
    objects_subclass2 = []
    for i in range(iters):
        subclass2 = _create_subclass2()
        objects_subclass2.append(subclass2())

    objects_subclass3 = []
    for i in range(iters):
        subclass3 = _create_subclass3()
        Class3.register(subclass3)
        objects_subclass3.append(subclass3())

    objects_subclass4 = []
    for i in range(iters):
        subclass4 = _create_subclass4()
        Class3.register(subclass4)
        objects_subclass4.append(subclass4())

    # create one more subclass for sibling check
    another_subclass1 = _create_subclass1()
    another_subclass2 = _create_subclass2()
    another_subclass3 = _create_subclass3()
    another_subclass4 = _create_subclass4()

    print("Created subclasses =", len(objects_subclass1) + len(objects_subclass2) + len(objects_subclass3) + len(objects_subclass4))
    print("Started compairing objects")

    # New subclass against parent, sibling, grantparent and cousin
    new_subclass1_vs_class1_ns = 0
    new_subclass1_vs_another_subclass1_ns = 0
    new_subclass1_vs_root_ns = 0
    new_subclass1_vs_class2_ns = 0
    for obj1 in objects_subclass1:
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        new_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        new_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        new_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        new_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    # Same subclass against parent, sibling, grantparent and cousin
    cached_subclass1_vs_root_ns = 0
    cached_subclass1_vs_another_subclass1_ns = 0
    cached_subclass1_vs_class1_ns = 0
    cached_subclass1_vs_class2_ns = 0
    for _ in range(iters):
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        cached_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        cached_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        cached_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        cached_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    # new class (via .register) against parent, sibling, grantparent and cousin
    new_subclass3_vs_class3_ns = 0
    new_subclass3_vs_another_subclass3_ns = 0
    new_subclass3_vs_root_ns = 0
    new_subclass3_vs_class1_ns = 0
    for obj3 in objects_subclass3:
        start = time.perf_counter_ns()
        assert isinstance(obj3, Class3)
        new_subclass3_vs_class3_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj3, another_subclass3)
        new_subclass3_vs_another_subclass3_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj3, Root)
        new_subclass3_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj3, Class1)
        new_subclass3_vs_class1_ns += time.perf_counter_ns() - start

    # same class (via .register) against parent, sibling, grantparent and cousin
    cached_subclass3_vs_class3_ns = 0
    cached_subclass3_vs_another_subclass3_ns = 0
    cached_subclass3_vs_root_ns = 0
    cached_subclass3_vs_class1_ns = 0
    for _ in range(iters):
        start = time.perf_counter_ns()
        assert isinstance(obj3, Class3)
        cached_subclass3_vs_class3_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj3, another_subclass3)
        cached_subclass3_vs_another_subclass3_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj3, Root)
        cached_subclass3_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj3, Class1)
        cached_subclass3_vs_class1_ns += time.perf_counter_ns() - start

    # new class (via __subclasses__) against parent, sibling, grantparent and cousin
    new_subclass4_vs_class4_ns = 0
    new_subclass4_vs_another_subclass4_ns = 0
    new_subclass4_vs_root_ns = 0
    new_subclass4_vs_class1_ns = 0
    for obj4 in objects_subclass4:
        start = time.perf_counter_ns()
        assert isinstance(obj4, Class4)
        new_subclass4_vs_class4_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj4, another_subclass4)
        new_subclass4_vs_another_subclass4_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj4, Root)
        new_subclass4_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj4, Class1)
        new_subclass4_vs_class1_ns += time.perf_counter_ns() - start

    # same class (via __subclasses__) against parent, sibling, grantparent and cousin
    cached_subclass4_vs_class4_ns = 0
    cached_subclass4_vs_another_subclass4_ns = 0
    cached_subclass4_vs_root_ns = 0
    cached_subclass4_vs_class1_ns = 0
    for _ in range(iters):
        start = time.perf_counter_ns()
        assert isinstance(obj4, Class4)
        cached_subclass4_vs_class4_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj4, another_subclass4)
        cached_subclass4_vs_another_subclass4_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj4, Root)
        cached_subclass4_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj4, Class1)
        cached_subclass4_vs_class1_ns += time.perf_counter_ns() - start

    print("Completed compairing classes.")
    print("isinstance(new class, parent), seconds:", new_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(new class, sibling), seconds:", new_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(new class, grandparent), seconds:", new_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(new class, cousin), seconds:", new_subclass1_vs_class2_ns / NS_PER_SECOND)

    print("isinstance(cached class, parent), seconds:", cached_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(cached class, sibling), seconds:", cached_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(cached class, grandparent), seconds:", cached_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(cached class, cousin), seconds:", cached_subclass1_vs_class2_ns / NS_PER_SECOND)

    print("isinstance(new class, parent via .register()), seconds:", new_subclass3_vs_class3_ns / NS_PER_SECOND)
    print("isinstance(new class, sibling via .register()), seconds:", new_subclass3_vs_another_subclass3_ns / NS_PER_SECOND)
    print("isinstance(new class, grandparent via .register()), seconds:", new_subclass3_vs_root_ns / NS_PER_SECOND)
    print("isinstance(new class, cousin via .register()), seconds:", new_subclass3_vs_class1_ns / NS_PER_SECOND)

    print("isinstance(cached class, parent via .register()), seconds:", cached_subclass3_vs_class3_ns / NS_PER_SECOND)
    print("isinstance(cached class, sibling via .register()), seconds:", cached_subclass3_vs_another_subclass3_ns / NS_PER_SECOND)
    print("isinstance(cached class, grandparent via .register()), seconds:", cached_subclass3_vs_root_ns / NS_PER_SECOND)
    print("isinstance(cached class, cousin via .register()), seconds:", cached_subclass3_vs_class1_ns / NS_PER_SECOND)

    print("isinstance(new class, parent via __subclasses__), seconds:", new_subclass4_vs_class4_ns / NS_PER_SECOND)
    print("isinstance(new class, sibling via __subclasses__), seconds:", new_subclass4_vs_another_subclass4_ns / NS_PER_SECOND)
    print("isinstance(new class, grandparent via __subclasses__), seconds:", new_subclass4_vs_root_ns / NS_PER_SECOND)
    print("isinstance(new class, cousin via __subclasses__), seconds:", new_subclass4_vs_class1_ns / NS_PER_SECOND)

    print("isinstance(cached class, parent via __subclasses__), seconds:", cached_subclass4_vs_class4_ns / NS_PER_SECOND)
    print("isinstance(cached class, sibling via __subclasses__), seconds:", cached_subclass4_vs_another_subclass4_ns / NS_PER_SECOND)
    print("isinstance(cached class, grandparent via __subclasses__), seconds:", cached_subclass4_vs_root_ns / NS_PER_SECOND)
    print("isinstance(cached class, cousin via __subclasses__), seconds:", cached_subclass4_vs_class1_ns / NS_PER_SECOND)

    print("Consumed memory, Mb:", psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)


if __name__ == "__main__":
    test_performance()
```
</details>

<details>
<summary>Before - 3.5Gb</summary>

```
  _py_abc:
    Created subclasses = 8000
    isinstance(new class, parent), seconds: 0.032312143
    isinstance(new class, sibling), seconds: 0.032560632
    isinstance(new class, grandparent), seconds: 0.022702893
    isinstance(new class, cousin), seconds: 46.402229165
    isinstance(cached class, parent), seconds: 0.005346288
    isinstance(cached class, sibling), seconds: 0.008571881
    isinstance(cached class, grandparent), seconds: 0.005353655
    isinstance(cached class, cousin), seconds: 0.008514126
    isinstance(new class, parent via .register()), seconds: 3.349354089
    isinstance(new class, sibling via .register()), seconds: 0.003968005
    isinstance(new class, grandparent via .register()), seconds: 131.716838481
    isinstance(new class, cousin via .register()), seconds: 0.018234704
    isinstance(cached class, parent via .register()), seconds: 0.005597478
    isinstance(cached class, sibling via .register()), seconds: 0.001133569
    isinstance(cached class, grandparent via .register()), seconds: 0.005487277
    isinstance(cached class, cousin via .register()), seconds: 0.008774221
    isinstance(new class, parent via __subclasses__), seconds: 0.39058178
    isinstance(new class, sibling via __subclasses__), seconds: 0.002374652
    isinstance(new class, grandparent via __subclasses__), seconds: 175.483922127
    isinstance(new class, cousin via __subclasses__), seconds: 0.020477199
    isinstance(cached class, parent via __subclasses__), seconds: 0.004526866
    isinstance(cached class, sibling via __subclasses__), seconds: 0.000965952
    isinstance(cached class, grandparent via __subclasses__), seconds: 0.004510054
    isinstance(cached class, cousin via __subclasses__), seconds: 0.007313503
    Consumed memory, Mb: 3470.0546875
```
</details>

<details>
<summary>After - 60Mb</summary>

```
  _py_abc:
    Created subclasses = 8000
    isinstance(new class, parent), seconds: 0.032962018
    isinstance(new class, sibling), seconds: 0.034775143
    isinstance(new class, grandparent), seconds: 0.02399701
    isinstance(new class, cousin), seconds: 70.297661371
    isinstance(cached class, parent), seconds: 0.005518908
    isinstance(cached class, sibling), seconds: 0.008924797
    isinstance(cached class, grandparent), seconds: 0.005529743
    isinstance(cached class, cousin), seconds: 0.008858091
    isinstance(new class via .register(), parent), seconds: 3.091385489
    isinstance(new class via .register(), sibling), seconds: 0.003439055
    isinstance(new class via .register(), grandparent), seconds: 142.118302431
    isinstance(new class via .register(), cousin), seconds: 71.150875384
    isinstance(cached class via .register(), parent), seconds: 0.004887914
    isinstance(cached class via .register(), sibling), seconds: 0.001010108
    isinstance(cached class via .register(), grandparent), seconds: 0.004776659
    isinstance(cached class via .register(), cousin), seconds: 0.007699287
    isinstance(new class via __subclasses__, parent), seconds: 12.981190242
    isinstance(new class via __subclasses__, sibling), seconds: 0.003357176
    isinstance(new class via __subclasses__, grandparent), seconds: 145.157514944
    isinstance(new class via __subclasses__, cousin), seconds: 71.294818072
    isinstance(cached class via __subclasses__, parent), seconds: 0.005243026
    isinstance(cached class via __subclasses__, sibling), seconds: 0.001126864
    isinstance(cached class via __subclasses__, grandparent), seconds: 0.005196655
    isinstance(cached class via __subclasses__, cousin), seconds: 0.008530414
    Consumed memory, Mb: 60.0703125
```
</details>

This doesn't affect cached version of isinstance/issubclass, but may slow down first check (before result is added to cache). IMHO, non-cached checks are not a real case that should be speed up.

For now, this is implemented only for pure Python `abc` module, C variant will take some time, as I'm new to Python C API.

**Comment by dolfinus** [comment]
pydantic's BaseModel uses ABCMeta only because this:
```python
from abc import ABCMeta

class BaseMeta(type):
    pass

class BaseModel(metaclass=BaseMeta):
  pass

class UserDefined(BaseModel, metaclass=ABCMeta):
  pass
```
fails with error:
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

So some users actually don't need ABCMeta `.register()` or `__subclasses__` handling at all, and the regular inheritance is just enough. There is a way to avoid these costly features by using custom metaclass (see https://github.com/pydantic/pydantic/pull/11669):
```python
from abc import ABCMeta
class CustomABCMeta(ABCMeta):
    __instancecheck__ = type.__instancecheck__
    __subclasscheck__ = type.__subclasscheck__

class Root(metaclass=CustomABCMeta):
    pass
```

This makes all isinstance/issubclass checks almost instantaneous:
<details>
<summary>39Mb</summary>

```python
#from abc import ABCMeta  # TODO
from _py_abc import ABCMeta
import time
import psutil
import os

NS_PER_SECOND = 1_000_000_000

class CustomABCMeta(ABCMeta):
    __instancecheck__ = type.__instancecheck__
    __subclasscheck__ = type.__subclasscheck__

class Root(metaclass=CustomABCMeta):
    pass

class Class1(Root):
    pass

class Class2(Root):
    pass


def _create_subclass1():
    class NestedClass1(Class1):
        pass

    return NestedClass1


def _create_subclass2():
    class NestedClass2(Class2):
        pass

    return NestedClass2


def test_performance():
    iters = 2000
    print("Creating new classes to check")
    objects_subclass1 = []
    for i in range(iters):
        subclass1 = _create_subclass1()
        objects_subclass1.append(subclass1())
    objects_subclass2 = []
    for i in range(iters):
        subclass2 = _create_subclass2()
        objects_subclass2.append(subclass2())

    # create one more subclass for sibling check
    another_subclass1 = _create_subclass1()
    another_subclass2 = _create_subclass2()

    print("Created subclasses =", len(objects_subclass1) + len(objects_subclass2))
    print("Consumed memory, Mb:", psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    print("Started compairing objects")

    # New subclass against parent, sibling, grantparent and cousin
    new_subclass1_vs_class1_ns = 0
    new_subclass1_vs_another_subclass1_ns = 0
    new_subclass1_vs_root_ns = 0
    new_subclass1_vs_class2_ns = 0
    for obj1 in objects_subclass1:
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        new_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        new_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        new_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        new_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    # Same subclass against parent, sibling, grantparent and cousin
    cached_subclass1_vs_root_ns = 0
    cached_subclass1_vs_another_subclass1_ns = 0
    cached_subclass1_vs_class1_ns = 0
    cached_subclass1_vs_class2_ns = 0
    for _ in range(iters):
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        cached_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        cached_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        cached_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        cached_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    print("Completed compairing classes.")
    print("Consumed memory, Mb:", psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)

    print("isinstance(cached class, parent), seconds:", cached_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(cached class, sibling), seconds:", cached_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(cached class, grandparent), seconds:", cached_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(cached class, cousin), seconds:", cached_subclass1_vs_class2_ns / NS_PER_SECOND)

    print("isinstance(new class, parent), seconds:", new_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(new class, sibling), seconds:", new_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(new class, grandparent), seconds:", new_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(new class, cousin), seconds:", new_subclass1_vs_class2_ns / NS_PER_SECOND)


if __name__ == "__main__":
    test_performance()
```

```
Creating new classes to check
Created subclasses = 4000
Consumed memory, Mb: 38.1015625
Started compairing objects
Completed compairing classes.
Consumed memory, Mb: 38.1015625

isinstance(cached class, parent), seconds: 0.001391204
isinstance(cached class, sibling), seconds: 0.001531258
isinstance(cached class, grandparent), seconds: 0.00140477
isinstance(cached class, cousin), seconds: 0.00156299

isinstance(new class, parent), seconds: 0.001600717
isinstance(new class, sibling), seconds: 0.00214647
isinstance(new class, grandparent), seconds: 0.001162172
isinstance(new class, cousin), seconds: 0.001685429
```
</details>

The results is almost the same as not using ABC at all:

<details>
<summary>39Mb</summary>

```python
import time
import psutil
import os

NS_PER_SECOND = 1_000_000_000

class Root:
    pass

class Class1(Root):
    pass

class Class2(Root):
    pass


def _create_subclass1():
    class NestedClass1(Class1):
        pass

    return NestedClass1


def _create_subclass2():
    class NestedClass2(Class2):
        pass

    return NestedClass2


def test_performance():
    iters = 4000
    print("Creating new classes to check")
    objects_subclass1 = []
    for i in range(iters):
        subclass1 = _create_subclass1()
        objects_subclass1.append(subclass1())
    objects_subclass2 = []
    for i in range(iters):
        subclass2 = _create_subclass2()
        objects_subclass2.append(subclass2())

    # create one more subclass for sibling check
    another_subclass1 = _create_subclass1()
    another_subclass2 = _create_subclass2()

    print("Created subclasses =", len(objects_subclass1) + len(objects_subclass2))
    print("Consumed memory, Mb:", psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    print("Started compairing objects")

    # New subclass against parent, sibling, grantparent and cousin
    new_subclass1_vs_class1_ns = 0
    new_subclass1_vs_another_subclass1_ns = 0
    new_subclass1_vs_root_ns = 0
    new_subclass1_vs_class2_ns = 0
    for obj1 in objects_subclass1:
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        new_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        new_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        new_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        new_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    # Same subclass against parent, sibling, grantparent and cousin
    cached_subclass1_vs_root_ns = 0
    cached_subclass1_vs_another_subclass1_ns = 0
    cached_subclass1_vs_class1_ns = 0
    cached_subclass1_vs_class2_ns = 0
    for _ in range(iters):
        start = time.perf_counter_ns()
        assert isinstance(obj1, Class1)
        cached_subclass1_vs_class1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, another_subclass1)
        cached_subclass1_vs_another_subclass1_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert isinstance(obj1, Root)
        cached_subclass1_vs_root_ns += time.perf_counter_ns() - start

        start = time.perf_counter_ns()
        assert not isinstance(obj1, Class2)
        cached_subclass1_vs_class2_ns += time.perf_counter_ns() - start

    print("Completed compairing objects.")
    print("Consumed memory, Mb:", psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)

    print("isinstance(cached class, parent), seconds:", cached_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(cached class, sibling), seconds:", cached_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(cached class, grandparent), seconds:", cached_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(cached class, cousin), seconds:", cached_subclass1_vs_class2_ns / NS_PER_SECOND)

    print("isinstance(new class, parent), seconds:", new_subclass1_vs_class1_ns / NS_PER_SECOND)
    print("isinstance(new class, sibling), seconds:", new_subclass1_vs_another_subclass1_ns / NS_PER_SECOND)
    print("isinstance(new class, grandparent), seconds:", new_subclass1_vs_root_ns / NS_PER_SECOND)
    print("isinstance(new class, cousin), seconds:", new_subclass1_vs_class2_ns / NS_PER_SECOND)


if __name__ == "__main__":
    test_performance()
```

```
Creating new classes to check
Created subclasses = 8000
Consumed memory, Mb: 39.28125
Started compairing objects
Completed compairing objects.
Consumed memory, Mb: 39.40625

isinstance(cached class, parent), seconds: 0.002001206
isinstance(cached class, sibling), seconds: 0.002153259
isinstance(cached class, grandparent), seconds: 0.001934674
isinstance(cached class, cousin), seconds: 0.002336402
isinstance(new class, parent), seconds: 0.002322098
isinstance(new class, sibling), seconds: 0.003058598
isinstance(new class, grandparent), seconds: 0.001834852
isinstance(new class, cousin), seconds: 0.002978064
```
</details>

This could be done only in user code, and should not be added to CPython or pydantic (IMHO).

**Comment by dolfinus** [comment]
> Probably explicit __subclasses__ = ... override should not be supported by ABCMeta at all

#150540 removes support for this case, as a demonstration. Diff is much smaller now.
