### ISSUE TITLE
comparison chaining has wrong source positions in most contexts (python 3.11.0rc2)

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#95921]
## problem
comparison chaining has wrong source positions in most contexts

``` python
>>> cnd = True                                            
>>> a = 1 if 1 in 2 == 3 else 0                                                                
Traceback (most recent call last):                                                              
  File "example.py", line 43, in <module>                                                             
    a = 1 if 1 in 2 == 3 else 0                                              
        ^^^^^^^^^^^^^^^^^^^^^^^                                                                  
TypeError: argument of type 'int' is not iterable  
```
This bug requires two things to happen:
1. The comparison chain has to contain more than on comparison the type does not matter (`==`,`in`,`<=`,`is`,...)
2. The context has to be something other than an expression

## no problem
The following examples work:
only one comparison
``` python
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    if 5<"5":
       ^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```
inside expression
``` python
>>> a=False or 4<"5"<6
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    a=False or 4<"5"<6
               ^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

## reason
The problem seems to be the positions in the compiled bytecode:

script:
```python
import dis

def foo():
    if 1<2<"no int":
        return 1
    return 0

for p in dis.get_instructions(foo):
    print(p.positions, p.opname,p.argval)
```

output (Python 3.11.0rc2+):
```python
Positions(lineno=4, end_lineno=4, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=5, end_lineno=5, col_offset=7, end_col_offset=8) LOAD_CONST 1
Positions(lineno=5, end_lineno=5, col_offset=9, end_col_offset=10) LOAD_CONST 2
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) SWAP 2
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) COPY 2
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) COMPARE_OP < # range of the whole if
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=5, end_lineno=5, col_offset=11, end_col_offset=19) LOAD_CONST no int
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) COMPARE_OP < # range of the whole if
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 38
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) JUMP_FORWARD 34
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) POP_TOP None
Positions(lineno=5, end_lineno=6, col_offset=4, end_col_offset=16) JUMP_FORWARD 38
Positions(lineno=6, end_lineno=6, col_offset=15, end_col_offset=16) LOAD_CONST 1
Positions(lineno=6, end_lineno=6, col_offset=15, end_col_offset=16) RETURN_VALUE None
Positions(lineno=7, end_lineno=7, col_offset=11, end_col_offset=12) LOAD_CONST 0
Positions(lineno=7, end_lineno=7, col_offset=11, end_col_offset=12) RETURN_VALUE None
```

the generated ast looks fine (snippet):

```
            If(
               test=Compare(
                  left=Constant(
                     value=1,
                     lineno=5,
                     col_offset=7, # correct
                     end_lineno=5,
                     end_col_offset=8),
                  ops=[
                     Lt(),
                     Lt()],
                  comparators=[
                     Constant(
                        value=2,
                        lineno=5,
                        col_offset=9, # correct
                        end_lineno=5,
                        end_col_offset=10),
                     Constant(
                        value='no int',
                        lineno=5,
                        col_offset=11, # correct
                        end_lineno=5,
                        end_col_offset=19)],
                  lineno=5,
                  col_offset=7,
                  end_lineno=5,
                  end_col_offset=19),

```

## other examples
here is a list of all the problems I found so far:

``` python
>>> if 4<"5"<6:
...     pass
...
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    if 4<"5"<6:
TypeError: '<' not supported between instances of 'int' and 'str'
>>> while 4<"5"<6:
...     pass
...
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    while 4<"5"<6:
TypeError: '<' not supported between instances of 'int' and 'str'

>>> assert 4<"5"<6
Traceback (most recent call last):
  File "example.py", line 27, in <module>
    assert 4<"5"<6
TypeError: '<' not supported between instances of 'int' and 'str'

>>> a=2+(5 if 4<"5"<6 else 3)
Traceback (most recent call last):
  File "example.py", line 29, in <module>
    a=2+(5 if 4<"5"<6 else 3)
         ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

>>> a=[a for a in [1] if 4<"5"<a ]
Traceback (most recent call last):
  File "example.py", line 34, in <listcomp>
    a=[a for a in [1] if 4<"5"<a ]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

>>> a={a for a in [1] if 4<"5"<a }
Traceback (most recent call last):
  File "example.py", line 35, in <setcomp>
    a={a for a in [1] if 4<"5"<a }
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

>>> a={a:a for a in [1] if 4<"5"<a }
Traceback (most recent call last):
  File "example.py", line 36, in <dictcomp>
    a={a:a for a in [1] if 4<"5"<a }
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

>>> a=list((a for a in [1] if 4<"5"<a ))
Traceback (most recent call last):
  File "example.py", line 37, in <genexpr>
    a=list((a for a in [1] if 4<"5"<a ))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

>>> cnd = True
>>> a = 1 if 1 in 2 == 3 else 0
Traceback (most recent call last):
  File "example.py", line 43, in <module>
    a = 1 if 1 in 2 == 3 else 0
        ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

>>> if True and 4<"5"<6:
...     pass
...
Traceback (most recent call last):
  File "example.py", line 45, in <module>
    if True and 4<"5"<6:
TypeError: '<' not supported between instances of 'int' and 'str'
```

## expected result

The positions should always match the ast-node range:

``` python
>>> a=list((a for a in [1] if 4<"5"<a ))
Traceback (most recent call last):
  File "example.py", line 37, in <genexpr>
    a=list((a for a in [1] if 4<"5"<a ))
                              ^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

or, even better only the failing comparison:

``` python
>>> a=list((a for a in [1] if 4<"5"<a ))
Traceback (most recent call last):
  File "example.py", line 37, in <genexpr>
    a=list((a for a in [1] if 4<"5"<a ))
                              ^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by 15r10nk** [comment]
I found a similar example which uses an if expression and a chain comparison:

```python
def f(s):
    return (s if (0 < s < 256) else "?")

import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)

f("abc")
```

output:
```
Positions(lineno=3, end_lineno=3, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=4, end_lineno=4, col_offset=18, end_col_offset=19) LOAD_CONST 0
Positions(lineno=4, end_lineno=4, col_offset=22, end_col_offset=23) LOAD_FAST s
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) SWAP 2
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) COPY 2
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) COMPARE_OP <
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=4, end_lineno=4, col_offset=26, end_col_offset=29) LOAD_CONST 256
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) COMPARE_OP <
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) POP_JUMP_FORWARD_IF_FALSE 38
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) JUMP_FORWARD 34
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) POP_TOP None
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=39) JUMP_FORWARD 38
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=13) LOAD_FAST s
Positions(lineno=4, end_lineno=4, col_offset=12, end_col_offset=13) JUMP_FORWARD 40
Positions(lineno=4, end_lineno=4, col_offset=36, end_col_offset=39) LOAD_CONST ?
Positions(lineno=4, end_lineno=4, col_offset=4, end_col_offset=40) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test9.py", line 12, in <module>
    f("abc")
  File "/home/frank/projects/executing/test9.py", line 4, in f
    return (s if (0 < s < 256) else "?")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

The error location is again expanded to the if expression and the source range of the `COMPARE_OP` is wrong.
This is probably the same issue.

Operator overloading is also not required, a failing comparison is enough.

**Comment by 15r10nk** [comment]
normal if expressions have the same problem

script:
```python
def f(s):
    if 0 < s < 256:
        return 5

import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f("abc")
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=8) LOAD_CONST 0
Positions(lineno=2, end_lineno=2, col_offset=11, end_col_offset=12) LOAD_FAST s
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=2, end_lineno=2, col_offset=15, end_col_offset=18) LOAD_CONST 256
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 40
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) JUMP_FORWARD 36
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_TOP None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) LOAD_CONST 5
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test9.py", line 11, in <module>
    f("abc")
  File "/home/frank/projects/executing/test9.py", line 2, in f
    if 0 < s < 256:
TypeError: '<' not supported between instances of 'int' and 'str'
```

The range of the `COMPARE_OP` spans the whole `if` expression.
This range can not be represented in the traceback.
I would expect that the `^^^^` signs are only under the `0 < s < 256`

**Comment by 15r10nk** [comment]
normal if statements have the same problem

script:
```python
def f(s):
    if 0 < s < 256:
        return 5

import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f("abc")
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=8) LOAD_CONST 0
Positions(lineno=2, end_lineno=2, col_offset=11, end_col_offset=12) LOAD_FAST s
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=2, end_lineno=2, col_offset=15, end_col_offset=18) LOAD_CONST 256
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 40
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) JUMP_FORWARD 36
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_TOP None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) LOAD_CONST 5
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test9.py", line 11, in <module>
    f("abc")
  File "/home/frank/projects/executing/test9.py", line 2, in f
    if 0 < s < 256:
TypeError: '<' not supported between instances of 'int' and 'str'
```

The range of the `COMPARE_OP` spans the whole `if` statement.
This range can not be represented in the traceback.
I would expect that the `^^^^` signs are only under the `0 < s < 256`

**Comment by 15r10nk** [comment]
normal if statements have the same problem

script:
```python
def f(s):
    if 0 < s < 256:
        return 5

import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f("abc")
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=8) LOAD_CONST 0
Positions(lineno=2, end_lineno=2, col_offset=11, end_col_offset=12) LOAD_FAST s
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=2, end_lineno=2, col_offset=15, end_col_offset=18) LOAD_CONST 256
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COMPARE_OP <
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 40
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) JUMP_FORWARD 36
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_TOP None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) LOAD_CONST 5
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test9.py", line 11, in <module>
    f("abc")
  File "/home/frank/projects/executing/test9.py", line 2, in f
    if 0 < s < 256:
TypeError: '<' not supported between instances of 'int' and 'str'
```

The range of the `COMPARE_OP` spans the whole `if` statement.
This range can not be represented in the traceback.
I would expect that the `^^^^` signs are only under the `0 < s < 256`

**Comment by 15r10nk** [comment]
The position range of `IS_OP` and all instructions for the comparison are also mapped to the whole if statement.
But I don't  know of any way how this can be observable in a traceback, because `is` is not throwing any exceptions as far as I know.
But it might be a good idea to fix it too.

script:
```python
def f(a,b):
    if a is b is None:
        return 5

import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f(1,2)
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=8) LOAD_FAST a
Positions(lineno=2, end_lineno=2, col_offset=12, end_col_offset=13) LOAD_FAST b
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) IS_OP 0 
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_FALSE 18
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_JUMP_FORWARD_IF_NOT_NONE 28
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) JUMP_FORWARD 24
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) POP_TOP None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) LOAD_CONST 5
Positions(lineno=3, end_lineno=3, col_offset=15, end_col_offset=16) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=16) RETURN_VALUE None
```
python version: Python 3.11.0rc1+

**Comment by 15r10nk** [comment]
The problem appears also if the comparison is inside a boolean operation:

script:
```python
def f(a, b):
    if a != b and b <= "A" == a:
        pass


import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f(1, 2)
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=8) LOAD_FAST a
Positions(lineno=2, end_lineno=2, col_offset=12, end_col_offset=13) LOAD_FAST b
Positions(lineno=2, end_lineno=2, col_offset=7, end_col_offset=13) COMPARE_OP !=
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_JUMP_FORWARD_IF_FALSE 52
Positions(lineno=2, end_lineno=2, col_offset=18, end_col_offset=19) LOAD_FAST b
Positions(lineno=2, end_lineno=2, col_offset=23, end_col_offset=26) LOAD_CONST A
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COMPARE_OP <=
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_JUMP_FORWARD_IF_FALSE 42
Positions(lineno=2, end_lineno=2, col_offset=30, end_col_offset=31) LOAD_FAST a
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COMPARE_OP ==
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_JUMP_FORWARD_IF_FALSE 56
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) JUMP_FORWARD 48
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_TOP None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) RETURN_VALUE None
Positions(lineno=3, end_lineno=3, col_offset=8, end_col_offset=12) LOAD_CONST None
Positions(lineno=3, end_lineno=3, col_offset=8, end_col_offset=12) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test10.py", line 12, in <module>
    f(1, 2)
  File "/home/frank/projects/executing/test10.py", line 2, in f
    if a != b and b <= "A" == a:
TypeError: '<=' not supported between instances of 'int' and 'str'
```
python version: Python 3.11.0rc1+


or a `not`

script:
```python
def f(a, b):
    if not b <= "A" == a:
        pass


import dis

for i in dis.get_instructions(f):
    print(i.positions, i.opname, i.argval)


f(1, 2)
```

output:
```python
Positions(lineno=1, end_lineno=1, col_offset=0, end_col_offset=0) RESUME 0
Positions(lineno=2, end_lineno=2, col_offset=11, end_col_offset=12) LOAD_FAST b
Positions(lineno=2, end_lineno=2, col_offset=16, end_col_offset=19) LOAD_CONST A
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) SWAP 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COPY 2
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COMPARE_OP <=
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_JUMP_FORWARD_IF_FALSE 30
Positions(lineno=2, end_lineno=2, col_offset=23, end_col_offset=24) LOAD_FAST a
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) COMPARE_OP ==
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_JUMP_FORWARD_IF_TRUE 36
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) JUMP_FORWARD 32
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) POP_TOP None
Positions(lineno=3, end_lineno=3, col_offset=8, end_col_offset=12) LOAD_CONST None
Positions(lineno=3, end_lineno=3, col_offset=8, end_col_offset=12) RETURN_VALUE None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) LOAD_CONST None
Positions(lineno=2, end_lineno=3, col_offset=4, end_col_offset=12) RETURN_VALUE None
Traceback (most recent call last):
  File "/home/frank/projects/executing/test10.py", line 12, in <module>
    f(1, 2)
  File "/home/frank/projects/executing/test10.py", line 2, in f
    if not b <= "A" == a:
TypeError: '<=' not supported between instances of 'int' and 'str'
```
python version: Python 3.11.0rc1+

**Comment by 15r10nk** [comment]
@brandtbucher I think this is related to #93691. 
Do you know if there someone already working on this?

Does it makes sense for me to look into it? I have (almost) no cpython core developer experience and it would take me probably far longer than someone else.

**Comment by brandtbucher** [comment]
Thanks for the detailed report. This issue seems to stem from the fact that we have two implementations of comparisons in the bytecode compiler: one generic version (`compiler_compare`) and one optimized for branching conditions (in `compiler_jump_if`). The latter doesn’t update the location to the current node, which is probably an oversight.

I’ll have a fix up either today or tomorrow. It will probably need to wait for 3.11.1, though.

**Comment by brandtbucher** [comment]
Thanks again for the great bug report!

**Comment by 15r10nk** [comment]
Big thank you for the quick bugfix @brandtbucher. But the fix caused another bug.

The `CALL` which creates the `AssertionError("msg")` gets now incorrect positions.

script:
```python


def func():
    assert a and b<c , "msg"

import dis
for i in dis.get_instructions(func):
    if i.opname in ("COMPARE_OP","CALL"):
        print(i.positions,i.opname,i.argval)
```

output (with your fix):
```python
Positions(lineno=4, end_lineno=4, col_offset=17, end_col_offset=20) COMPARE_OP <
Positions(lineno=4, end_lineno=4, col_offset=17, end_col_offset=20) CALL 0
```
You see that the positions of the `CALL` are equal to the positions of the `b<c`.

output (the commit before your fix):
```python
Positions(lineno=4, end_lineno=4, col_offset=17, end_col_offset=20) COMPARE_OP <
Positions(lineno=4, end_lineno=4, col_offset=4, end_col_offset=28) CALL 0
```
The positions of the `CALL` is here the whole `assert` statement (which is ok for me, because it is easy to handle).

This did not cause any incorrect Tracebacks (at least I don't know how to produce it), but can cause problems for tools which analyse this positions.

**Comment by 15r10nk** [comment]
It is maybe also important that this is not the only example.
``` python
    assert b<c , "msg"
    assert a<b<c , "msg"
    assert a+b<c , "msg"
```
show the same problems. I looks like everything with one or more `<` causes this problem.

**Comment by brandtbucher** [comment]
Yep, I see the issue. My patch sets the location when recursing into the expression, but doesn't restore it after.

**Comment by brandtbucher** [comment]
I have a working fix for 3.11 and 3.10, just need to write a decent regression test. I'll pick it back up tomorrow.

**Comment by 15r10nk** [comment]
can you please point me to the commit which fixes this issue. I would like to run the executing testsuite against it.

**Comment by hauntsaninja** [comment]
Was going through older issues, looks like this is still an issue on 3.11. Brandt do you still have your branch?

**Comment by StanFromIreland** [comment]
Is there anything left to do here, the reported issue and later regression are fixed from my testing?

**Comment by picnixz** [comment]
I'm going to close this one as `completed`. If there are still problems, let's open a new issue (but add a ref to this one).

**Comment by hauntsaninja** [comment]
There is still an issue on Python 3.11, but I guess that is no longer in bugfix :-) Thanks 15r10nk and brandtbucher!
